### ISSUE TITLE
OpenCppCoverage VS plugin doesn't work on VS2015

### ISSUE THREAD

**Issue by DieSlower** [OpenCppCoverage/OpenCppCoverage#1]
I'm having the exact same problem that is described in "OpenCppCoverage VS plugin doesn't work on solutions generated by cmake" on codeplex. 

I'm using VS2015u3 and it looks like the plugin is version 0.9.4.0, it looks like that is the latest available on the MS downloads. 

The Error I get is: 

> System.InvalidOperationException: Cannot find tool: VCCLCompilerTool
>    at OpenCppCoverage.VSPackage.DynamicVCConfiguration.GetTool(Object configuration, String toolKind)
>    at OpenCppCoverage.VSPackage.DynamicVCConfiguration..ctor(Object configuration)
>    at CallSite.Target(Closure , CallSite , Type , Object )
>    at OpenCppCoverage.VSPackage.DynamicVCProject.get_Configurations()
>    at OpenCppCoverage.VSPackage.ConfigurationManager.ComputeConfiguration(ExtendedProject project, SolutionContext context, String& error)
>    at OpenCppCoverage.VSPackage.ConfigurationManager.ComputeConfiguration(SolutionConfiguration2 activeConfiguration, ExtendedProject project, String& error)
>    at OpenCppCoverage.VSPackage.ConfigurationManager.FindConfiguration(SolutionConfiguration2 activeConfiguration, ExtendedProject project)
>    at OpenCppCoverage.VSPackage.Settings.StartUpProjectSettingsBuilder.BuildCppProject(SolutionConfiguration2 activeConfiguration, IConfigurationManager configurationManager, List`1 projects)
>    at OpenCppCoverage.VSPackage.Settings.StartUpProjectSettingsBuilder.ComputeOptionalSettings(SolutionConfiguration2 activeConfiguration)
>    at OpenCppCoverage.VSPackage.Settings.StartUpProjectSettingsBuilder.ComputeSettings()
>    at OpenCppCoverage.VSPackage.Settings.UI.MainSettingController.UpdateStartUpProject()
>    at OpenCppCoverage.VSPackage.Settings.MainSettingsManager.ShowSettingsWindows(CoverageRunner coverageRunner)
>    at OpenCppCoverage.VSPackage.OpenCppCoveragePackage.<>c__DisplayClass2_0.<MenuItemCallback>b__0()
>    at OpenCppCoverage.VSPackage.ErrorHandler.<>c__DisplayClass6_0.<Execute>b__0()
>    at OpenCppCoverage.VSPackage.ErrorHandler.<ExecuteAsync>d__5.MoveNext()

I saw this reply: 

> Hello,
> 
> Thank you for reporting this issue.
> I reproduced the problem thanks to your example. Unloading ZERO_CHECK project avoid the error for me.
> I am going to release a new version of the plugin soon (something like end of July) and so I will add a fix for this issue.
> 
> Please let me know if the workaround helps you.
> 
> OpenCppCoverage

Has the fix been committed? Is there a new version of this plugin? Where can I download it?

V/R,
--Maxim

**Comment by OpenCppCoverage** [comment]
Hello,

You can try one of the following things:
- Unload all projects without compilation
- Build master branch of the plugin https://github.com/OpenCppCoverage/OpenCppCoveragePlugin. Fix has been committed but not fully tested.
- Wait few days for the next release (something like a week)

I hope it will help,

OpenCppCoverage

**Comment by DieSlower** [comment]
Thank you for the quick response,

I attempted to build the master branch, but it does not have a VS2015 solution. When I try to open the VS2013 solution in VS2015 it says that some projects are incompatible. 

Do you have a VS2015 solution? Or do we need to build this code with a different VS that will also work with 2015?

V/R,
--Maxim

**Comment by DieSlower** [comment]
Hmm....I also attempted to open the 2013 project in VS2013 Pro and got the following error:

VSPackage\VSPackageVS2013.csproj: The project 'VSPackageVS2013.csproj' was created with a newer version of Visual Studio which is incompatible with your version. You can only open this project with newer versions of Visual Studio.
Was this 2013 project by some chance created with VS2017?
I was testing this with VS2013 Update 5 and VS2015 update 3

**Comment by OpenCppCoverage** [comment]
Hello,

Both solutions are Visual Studio 2017 solutions. Please see the updated page: https://github.com/OpenCppCoverage/OpenCppCoveragePlugin for more information.

I think it will be easier to wait a few days for the release.

OpenCppCoverage

**Comment by DieSlower** [comment]
Hello,

Are there any news on the plugin release? 
I attempted to build the VS2013 solution in vs2017 but it gave me an error saying that some boost library was missing. 

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(600,5): error VSSDK1025: Could not add the file "OpenCppCoverage-x64\boost_chrono-vc140-mt-1_59.dll" to the zip package "bin\Release\VSPackage.vsix". Could not find file 

> 'D:\Development\OpenCppCoveragePlugin-master\VSPackage\OpenCppCoverage-x64\boost_chrono-vc140-mt-1_59.dll'.

Is there a list of external dependencies that is supposed to come with this?

V/R,
--Maxim

**Comment by OpenCppCoverage** [comment]
Hello,

The release was postponed for a few days because of another issue.
Now [OpenCppCoverage Plugin 0.9.4.1](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/releases/tag/0.9.4.1) is available and should fix this issue.

Let me know if it solves your problem.

OpenCppCoverage

**Comment by DieSlower** [comment]
Thanks! That made the window work!

I'm having a little trouble though. I can only run one unit test exe file at a time. Is there a way to just load and run all the unit test files/projects in the solution?

The wiki did not have anything about that...
https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/wiki


--Maxim

**Comment by OpenCppCoverage** [comment]
Hello,

OpenCppCoverage plugin only supports one executable at a time. You may consider using [--input_coverage](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki#merging-coverage---input_coverage----export_typebinary) from OpenCppCoverage command line.

I hope it will help,

OpenCppCoverage
