### ISSUE TITLE
Is there a way to regenerate the report?

### ISSUE THREAD

**Issue by sprinaj** [OpenCppCoverage/OpenCppCoverage#10]
**Before creating an issue, please make sure the answer is not in the [FAQ](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ).**

**This template is applied for all bug requests. Remove it for other general question or feature request.**

## Describe your environment
- Version of OpenCppCoverage: ___OpenCppCoverageSetup-x64-0.9.2__
- Architecture (x86/ x64): __ x64___
- Windows version: ___win7__

## Describe your problem
Steps to reproduce:
Use the command line mode to start the service. After the test is finished, the service stops normally. There is no end of the command line, the ctrl+c is forced to quit, no coverage report is generated, and is there a way to regenerate the report?

Could you reproduce the issue on a toy example?

## Attached file
Attach the log file *LastCoverageResults.log*, located in your current folder.

If the report does not contain the expected files, please run OpenCppCoverage with ```--verbose``` flag. This will add more information into *LastCoverageResults.log*.

**Comment by OpenCppCoverage** [comment]
Hello,

I am not sure to understand your problem. What do you mean by _"the service stops normally"_? 
_"no coverage report is generated"_ so OpenCppCoverage does not stop normally.

_"is there a way to regenerate the report?"_ 
If nothing was generated, you need to run again the computation of the coverage. I am not sure to understand the question.

Can you provide _LastCoverageResults.log_ and explain step by step your problem?
Can you reproduce it on a toy example?

OpenCppCoverage

**Comment by mladenmilev** [comment]
@sprinaj, I understand the question as I have same experience (can reproduce) with Microsoft Visual C++ code with Google Test.

The test project compiles/links and produces Test.exe

Then I open CMD and start the OpenCppcoverage with for that Test.exe (windows 7 enterprise, 64 bit) the test run and then the OpenCppCoverage did not generate the report (seems like hoocked) until I press "Enter" key. 

Once pressed "Enter" the CMD prints the report is generated and it actually is generated at that time. 
but if you wait 5 min before pressing the "Enter" key though tests would have finished still no report would be generated. Generation is after the "Enter" key event. 
Strange behavior for command prompt actually. I can confirm. I use latest OpenCppCoverage 0.9.6.1

On the other hand when I integrated the OpenCppCoverage within Jenkins and from Jenkins I call Windows CMD batch command it is running just fine. 

Go figure it out! I have no clue though why simple CMD from windows differs from Jenkins Windows batch command.

**Comment by OpenCppCoverage** [comment]
Hello,

Thanks for the feedback.
Any chance it is related to https://opencppcoverage.codeplex.com/discussions/647459?
If not, do you have the issue with a "Hello World" application?
Can you reproduce the issue on a small project so that I can fix it?

I hope it will help,

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

Feel free to reopen this issue if you have more information.

OpenCppCoverage
