### ISSUE TITLE
The collecting will be finished when I testing

### ISSUE THREAD

**Issue by luoyexiaohe** [OpenCppCoverage/OpenCppCoverage#107]
as normally , the collecting will be finished when I shutdown my program. but this time, I didn't shutdown my program while the  collecting finished .
what's the reason ? Does something wrong with my program or yours ?
note:my program doesn't hava a exit. I allways shutdown it by taskmanager.

**Comment by OpenCppCoverage** [comment]
Hi,

If OpenCppCoverage has an issue, it exits and does not create the coverage report. 
It may be possible your program exited abnormally and then OpenCppCoverage created a coverage report. In this case, in the main page of the HTML report you should have the message `"Warning: Your program has exited with error code: "`.

I hope it helps,

OpenCppCoverage

**Comment by luoyexiaohe** [comment]
thanks , I forgot to close this question.
