### ISSUE TITLE
Build ThirdParty fails

### ISSUE THREAD

**Issue by IOTeule** [OpenCppCoverage/OpenCppCoverage#108]
**Describe the bug**
Can't Compile, 
maybe root cause is https://github.com/microsoft/vcpkg/issues/6946

Error: Building package zlib:x64-windows failed with: BUILD_FAILED
Error: Building package protobuf:x64-windows failed with: BUILD_FAILED
Error: Building package gtest:x64-windows failed with: BUILD_FAILED
Error: Building package ctemplate:x64-windows failed with: BUILD_FAILED
Error: Building package boost-system:x64-windows failed with: BUILD_FAILED
Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Error: Building package boost-container:x64-windows failed with: BUILD_FAILED
Error: Building package boost-atomic:x64-windows failed with: BUILD_FAILED
Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Error: Building package boost-system:x64-windows failed with: BUILD_FAILED
Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Error: Building package boost-system:x64-windows failed with: BUILD_FAILED
Error: Building package boost-atomic:x64-windows failed with: BUILD_FAILED
Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Error: Building package range-v3:x64-windows failed with: BUILD_FAILED

**To Reproduce**
- git clone + Run batch BuildThirdPartyDependencies.bat

Upload the log file LastCoverageResults.log.
- there is no such file

**Expected behavior**
- the compilation should work

**Desktop (please complete the following information):**
- Version of OpenCppCoverage: OpenCppCoverage 0.9.8.0
- Architecture (x86/ x64): x64
- Windows version: Win 10 Enterprise LTSC
- Compiler: 

Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.03190

**Additional context**
It would have been helpful to add a how to build section in the README.MD

**Comment by OpenCppCoverage** [comment]
Hello,

Thank you for reporting this issue. The third party libraries should compile fine now.

**OpenCppCoverage requires Visual Studio 2019 16.4.X.** See [Building OpenCppCoverage](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Building-OpenCppCoverage) for instructions.

I hope it helps,

OpenCppCoverage
