### ISSUE TITLE
CMake-based build system

### ISSUE THREAD

**Issue by Pospelove** [OpenCppCoverage/OpenCppCoverage#112]
I suggest switching to a CMake-based build system for the next reasons:

- More smooth handling of different VS versions.
- Allow running tests from the command-line. I understand that the current test system may be already comfortable to use for the maintainer, but I think using CTest will make it more usable for contributors.
- Fetch dependencies automatically when CMake generation is performing. [PMM](https://github.com/vector-of-bool/pmm) can be used for this purpose. We also could install only the dependencies required for the target architecture skipping `vcpkg install x64-*` commands when we want to build a 32bit app and so.
- Simplify future integration with CMake scripts (#85).

I already have written CMakeLists.txt for this project for personal usage
(see https://github.com/Pospelove/OpenCppCoverage/commit/28fc818447e59dcac4c5fc22177eb261be5bcc80#diff-af3b638bc2a3e6c650974192a53c7291). I may finish it and submit a PR if it's really needed for your project.

**Comment by amai2012** [comment]
That might help with https://github.com/OpenCppCoverage/OpenCppCoverage/pull/113 ...

**Comment by OpenCppCoverage** [comment]
Hello,

Thank you for providing feedback!
For now, I do not plan to migrate OpenCppCoverage to CMakefile.

> More smooth handling of different VS versions.

I do not know if the current code compiles with Visual Studio 2017. I also noticed some compilation issues between minor versions of Visual Studio. I would like to avoid testing compilation for every version of Visual Studio.

> Allow running tests from the command-line.

As unit tests are written with GTest, you can run unit tests from the command-line.

> Fetch dependencies automatically when CMake generation is performing

As far as I know, running `BuildThirdPartyDependencies.bat` handles dependencies automatically (Except for `msdia140.dll`). Dlls are also copied to the output folder. Let me know if it is not the case. 

I will help on https://github.com/OpenCppCoverage/OpenCppCoverage/pull/113.

OpenCppCoverage.

**Comment by Pospelove** [comment]
OK, got it. Closing this for now. Thanks.
