### ISSUE TITLE
build opencppcoverage error 

### ISSUE THREAD

**Issue by melissalu** [OpenCppCoverage/OpenCppCoverage#119]
follow wiki https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Building-OpenCppCoverage
but I get errors:

-- Using cached D:/code/OpenCppCoverage/Build/ThirdParty/vcpkg/downloads/OlafvdSpek-ctemplate-4b7e6c52dc7cbb4d51c9abcebcbac91ec256a62b.tar.gz
-- Using source at D:/code/OpenCppCoverage/Build/ThirdParty/vcpkg/buildtrees/ctemplate/src/1ec256a62b-c7b6f00c13
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/code/OpenCppCoverage/Build/ThirdParty/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: D:/code/OpenCppCoverage/Build/ThirdParty/vcpkg/buildtrees/ctemplate/x64-windows-dbg
    See logs for more information:
      D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/ctemplate/portfile.cmake:22 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package ctemplate:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ctemplate:x64-windows
  Vcpkg version: 2020.01.17-nohash

build output file info as follower:
[1/16] C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe   /TP -D_VARIADIC_MAX=10 -Dlibctemplate_EXPORTS -Iinclude /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /W3 /wd4005 /wd4996 /wd4018 -D_CRT_SECURE_NO_WARNINGS /showIncludes /FoCMakeFiles\libctemplate.dir\src\htmlparser\jsparser.cc.obj /FdCMakeFiles\libctemplate.dir\ /FS -c D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\jsparser.cc
FAILED: CMakeFiles/libctemplate.dir/src/htmlparser/jsparser.cc.obj 
C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe   /TP -D_VARIADIC_MAX=10 -Dlibctemplate_EXPORTS -Iinclude /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /W3 /wd4005 /wd4996 /wd4018 -D_CRT_SECURE_NO_WARNINGS /showIncludes /FoCMakeFiles\libctemplate.dir\src\htmlparser\jsparser.cc.obj /FdCMakeFiles\libctemplate.dir\ /FS -c D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\jsparser.cc
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\jsparser.cc(125): error C2065: 'JSPARSER_NUM_STATES': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\jsparser.cc(127): error C2065: 'jsparser_states_external': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\jsparser.cc(467): error C2065: 'JSPARSER_STATE_INT_JS_REGEXP_SLASH': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\jsparser.cc(474): error C2065: 'JSPARSER_STATE_INT_JS_REGEXP_SLASH': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\jsparser.cc(499): error C2065: 'JSPARSER_STATE_INT_JS_REGEXP_SLASH': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\jsparser.cc(505): error C2065: 'JSPARSER_STATE_INT_JS_REGEXP_SLASH': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\jsparser.cc(546): error C2065: 'JSPARSER_NUM_STATES': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\jsparser.cc(551): error C2065: 'jsparser_state_transitions': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\jsparser.cc(552): error C2065: 'jsparser_states_internal_names': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\jsparser.cc(554): error C2065: 'JSPARSER_STATE_INT_JS_TEXT': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\jsparser.cc(556): error C2065: 'JSPARSER_STATE_INT_JS_SLASH': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\jsparser.cc(558): error C2065: 'JSPARSER_STATE_INT_JS_COMMENT_AFTER': undeclared identifier
[2/16] C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe   /TP -D_VARIADIC_MAX=10 -Dlibctemplate_EXPORTS -Iinclude /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /W3 /wd4005 /wd4996 /wd4018 -D_CRT_SECURE_NO_WARNINGS /showIncludes /FoCMakeFiles\libctemplate.dir\src\htmlparser\statemachine.cc.obj /FdCMakeFiles\libctemplate.dir\ /FS -c D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\statemachine.cc
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

[3/16] C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe   /TP -D_VARIADIC_MAX=10 -Dlibctemplate_EXPORTS -Iinclude /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /W3 /wd4005 /wd4996 /wd4018 -D_CRT_SECURE_NO_WARNINGS /showIncludes /FoCMakeFiles\libctemplate.dir\src\htmlparser\htmlparser.cc.obj /FdCMakeFiles\libctemplate.dir\ /FS -c D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc
FAILED: CMakeFiles/libctemplate.dir/src/htmlparser/htmlparser.cc.obj 
C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe   /TP -D_VARIADIC_MAX=10 -Dlibctemplate_EXPORTS -Iinclude /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /W3 /wd4005 /wd4996 /wd4018 -D_CRT_SECURE_NO_WARNINGS /showIncludes /FoCMakeFiles\libctemplate.dir\src\htmlparser\htmlparser.cc.obj /FdCMakeFiles\libctemplate.dir\ /FS -c D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(102): error C2065: 'htmlparser_states_external': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(591): error C2065: 'HTMLPARSER_STATE_INT_CDATA_TEXT': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(597): error C2065: 'HTMLPARSER_STATE_INT_CDATA_TEXT': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(648): error C2065: 'HTMLPARSER_STATE_INT_CDATA_TEXT': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(667): error C2065: 'HTMLPARSER_STATE_INT_TEXT': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(670): error C2065: 'HTMLPARSER_STATE_INT_JS_FILE': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(674): error C2065: 'HTMLPARSER_STATE_INT_CSS_FILE': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(677): error C2065: 'HTMLPARSER_STATE_INT_TAG_SPACE': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(706): error C2065: 'HTMLPARSER_NUM_STATES': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(710): error C2065: 'htmlparser_state_transitions': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(711): error C2065: 'htmlparser_states_internal_names': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(713): error C2065: 'HTMLPARSER_STATE_INT_TAG_NAME': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(715): error C2065: 'HTMLPARSER_STATE_INT_TAG_NAME': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(717): error C2065: 'HTMLPARSER_STATE_INT_ATTR': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(718): error C2065: 'HTMLPARSER_STATE_INT_ATTR': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(720): error C2065: 'HTMLPARSER_STATE_INT_TAG_CLOSE': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(726): error C2065: 'HTMLPARSER_STATE_INT_CDATA_TEXT': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(727): error C2065: 'HTMLPARSER_STATE_INT_CDATA_COMMENT_START': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(729): error C2065: 'HTMLPARSER_STATE_INT_CDATA_COMMENT_START_DASH': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(731): error C2065: 'HTMLPARSER_STATE_INT_CDATA_COMMENT_BODY': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(733): error C2065: 'HTMLPARSER_STATE_INT_CDATA_COMMENT_DASH': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(735): error C2065: 'HTMLPARSER_STATE_INT_CDATA_COMMENT_DASH_DASH': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(737): error C2065: 'HTMLPARSER_STATE_INT_CDATA_LT': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(738): error C2065: 'HTMLPARSER_STATE_INT_CDATA_MAY_CLOSE': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(742): error C2065: 'HTMLPARSER_STATE_INT_JS_FILE': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(744): error C2065: 'HTMLPARSER_STATE_INT_CDATA_MAY_CLOSE': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(746): error C2065: 'HTMLPARSER_STATE_INT_CDATA_MAY_CLOSE': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(749): error C2065: 'HTMLPARSER_STATE_INT_VALUE': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(752): error C2065: 'HTMLPARSER_STATE_INT_VALUE_TEXT': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(754): error C2065: 'HTMLPARSER_STATE_INT_VALUE_Q': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(756): error C2065: 'HTMLPARSER_STATE_INT_VALUE_DQ': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(760): error C2065: 'HTMLPARSER_STATE_INT_VALUE_TEXT': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(762): error C2065: 'HTMLPARSER_STATE_INT_VALUE_Q': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(764): error C2065: 'HTMLPARSER_STATE_INT_VALUE_DQ': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(767): error C2065: 'HTMLPARSER_STATE_INT_VALUE_TEXT': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(768): error C2065: 'HTMLPARSER_STATE_INT_VALUE_Q': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(769): error C2065: 'HTMLPARSER_STATE_INT_VALUE_DQ': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(852): error C2065: 'HTMLPARSER_STATE_INT_VALUE_Q_START': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(853): error C2065: 'HTMLPARSER_STATE_INT_VALUE_Q': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(854): error C2065: 'HTMLPARSER_STATE_INT_VALUE_DQ_START': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(855): error C2065: 'HTMLPARSER_STATE_INT_VALUE_DQ': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(871): error C2065: 'HTMLPARSER_STATE_INT_CDATA_TEXT': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(872): error C2065: 'HTMLPARSER_STATE_INT_CDATA_COMMENT_START': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(873): error C2065: 'HTMLPARSER_STATE_INT_CDATA_COMMENT_START_DASH': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(874): error C2065: 'HTMLPARSER_STATE_INT_CDATA_COMMENT_BODY': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(875): error C2065: 'HTMLPARSER_STATE_INT_CDATA_COMMENT_DASH': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(876): error C2065: 'HTMLPARSER_STATE_INT_CDATA_COMMENT_DASH_DASH': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(877): error C2065: 'HTMLPARSER_STATE_INT_CDATA_LT': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(878): error C2065: 'HTMLPARSER_STATE_INT_CDATA_MAY_CLOSE': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(879): error C2065: 'HTMLPARSER_STATE_INT_JS_FILE': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(924): error C2065: 'HTMLPARSER_STATE_INT_CSS_FILE': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(1076): error C2065: 'HTMLPARSER_STATE_INT_VALUE': undeclared identifier
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\htmlparser.cc(1077): error C2065: 'HTMLPARSER_STATE_INT_VALUE_TEXT': undeclared identifier
[4/16] C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe   /TP -D_VARIADIC_MAX=10 -Dlibctemplate_EXPORTS -Iinclude /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /W3 /wd4005 /wd4996 /wd4018 -D_CRT_SECURE_NO_WARNINGS /showIncludes /FoCMakeFiles\libctemplate.dir\src\template_annotator.cc.obj /FdCMakeFiles\libctemplate.dir\ /FS -c D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\template_annotator.cc
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

[5/16] C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe   /TP -D_VARIADIC_MAX=10 -Dlibctemplate_EXPORTS -Iinclude /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /W3 /wd4005 /wd4996 /wd4018 -D_CRT_SECURE_NO_WARNINGS /showIncludes /FoCMakeFiles\libctemplate.dir\src\template_modifiers.cc.obj /FdCMakeFiles\libctemplate.dir\ /FS -c D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\template_modifiers.cc
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

d:\code\opencppcoverage\build\thirdparty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\base/util.h(184): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\x64-windows-dbg\include\ctemplate/template_modifiers.h(212): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\template_modifiers.cc(456): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
[6/16] C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe   /TP -D_VARIADIC_MAX=10 -Dlibctemplate_EXPORTS -Iinclude /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /W3 /wd4005 /wd4996 /wd4018 -D_CRT_SECURE_NO_WARNINGS /showIncludes /FoCMakeFiles\libctemplate.dir\src\base\arena.cc.obj /FdCMakeFiles\libctemplate.dir\ /FS -c D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\base\arena.cc
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\x64-windows-dbg\include\base/util.h(184): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
[7/16] C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe   /TP -D_VARIADIC_MAX=10 -Dlibctemplate_EXPORTS -Iinclude /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /W3 /wd4005 /wd4996 /wd4018 -D_CRT_SECURE_NO_WARNINGS /showIncludes /FoCMakeFiles\libctemplate.dir\src\per_expand_data.cc.obj /FdCMakeFiles\libctemplate.dir\ /FS -c D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\per_expand_data.cc
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

[8/16] C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe   /TP -D_VARIADIC_MAX=10 -Dlibctemplate_EXPORTS -Iinclude /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /W3 /wd4005 /wd4996 /wd4018 -D_CRT_SECURE_NO_WARNINGS /showIncludes /FoCMakeFiles\libctemplate.dir\src\template_cache.cc.obj /FdCMakeFiles\libctemplate.dir\ /FS -c D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\template_cache.cc
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\x64-windows-dbg\include\ctemplate/template_modifiers.h(212): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
[9/16] C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe   /TP -D_VARIADIC_MAX=10 -Dlibctemplate_EXPORTS -Iinclude /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /W3 /wd4005 /wd4996 /wd4018 -D_CRT_SECURE_NO_WARNINGS /showIncludes /FoCMakeFiles\libctemplate.dir\src\template_dictionary.cc.obj /FdCMakeFiles\libctemplate.dir\ /FS -c D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\template_dictionary.cc
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

d:\code\opencppcoverage\build\thirdparty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\base/util.h(184): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\x64-windows-dbg\include\ctemplate/template_modifiers.h(212): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
[10/16] C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe   /TP -D_VARIADIC_MAX=10 -Dlibctemplate_EXPORTS -Iinclude /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /W3 /wd4005 /wd4996 /wd4018 -D_CRT_SECURE_NO_WARNINGS /showIncludes /FoCMakeFiles\libctemplate.dir\src\template.cc.obj /FdCMakeFiles\libctemplate.dir\ /FS -c D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\template.cc
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

D:\code\OpenCppCoverage\Build\ThirdParty\vcpkg\buildtrees\ctemplate\x64-windows-dbg\include\ctemplate/template_modifiers.h(212): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
d:\code\opencppcoverage\build\thirdparty\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\base/util.h(184): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
ninja: build stopped: subcommand failed.

**Comment by OpenCppCoverage** [comment]
Hi,

This kind of errors usually happens when the version of Visual Studio is not **16.4.X**.
Anyway, I have simplified the way to install third party libraries: https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Building-OpenCppCoverage#install-third-party-libraries.

Let me know if you have any trouble with the new instructions.

OpenCppCoverage.
