### ISSUE TITLE
Get total coverage

### ISSUE THREAD

**Issue by Maxxan** [OpenCppCoverage/OpenCppCoverage#12]
It would be good if the html report also had a summary of covered lines. For example:
Module A 40% coverage, 100 lines total, (40 lines covered)
Module B 70% coverage, 100 lines total, (70 lines covered)

Total coverage: 55%. 200 lines total, (110 lines covered)

**Comment by OpenCppCoverage** [comment]
Hello,

Sorry for my late answer.
You can use Cobertura export to have a global coverage by adding ```--export_type=html --export_type=cobertura```.
In the file _YOUR_PROGRAM_NAME.xml_, on the second line, you have the global coverage.

```<coverage line-rate="0.13422818791946309" ...```

I will add this feature when I need to update the HTML report.

I hope it will help,

OpenCppCoverage

**Comment by Maxxan** [comment]
Thanks for your feedback! I'm looking forward to next update!

**Comment by OpenCppCoverage** [comment]
Hello,

It should be availabe in [OpenCppCoverage 0.9.7.0](https://github.com/OpenCppCoverage/OpenCppCoverage/releases/tag/release-0.9.7.0).

OpenCppCoverage
