### ISSUE TITLE
Fix regexp in Wiki

### ISSUE THREAD

**Issue by pavelkryukov** [OpenCppCoverage/OpenCppCoverage#122]
**Describe the bug**
Wiki contains wrong regexp: `"\s*{.*"` in that paragraph: https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ#else-or--is-not-marked-as-covered.

**Expected behavior**
`\s*\}.*`, note the **_closing_** bracket and escaping.

**Comment by OpenCppCoverage** [comment]
Hi @pavelkryukov ,

Thank you for reporting this issue. Documentation was updated.

OpenCppCoverage.

**Comment by pavelkryukov** [comment]
Thanks!
