### ISSUE TITLE
Branch/Decision coverage feature

### ISSUE THREAD

**Issue by chaithanyagrb** [OpenCppCoverage/OpenCppCoverage#127]
Hi,
The coverage report currently shows line coverage.  Is there an option to enable reporting decision or condition coverage so that we can identify the outcome of every decision/condition.

Thanks,
Chaithanya.

**Comment by WimLeflere** [comment]
Branch coverage is not planned, see #20

**Comment by chaithanyagrb** [comment]
Thank you
