### ISSUE TITLE
The tool doesn't exclude sources, marked as --exclude-sources when merging coverage data / creating html reports.

### ISSUE THREAD

**Issue by yaav** [OpenCppCoverage/OpenCppCoverage#13]
I have a set of *.cov files, collected during test runs and now want to exclude all header files from the report.
But when I set --exclude-sources \"<code location\>\*.h" nothing happens. All headers are still in the report.

**Comment by OpenCppCoverage** [comment]
Hello,

``--exclude-sources`` is only used when running a program and has no interaction with ``--input_coverage``.

In your case, you need to use ``--exclude-sources`` when generating the cov file.
I will add a warning when ``--exclude-sources`` is used without a program to run.

I hope it will help,

OpenCppCoverage
