### ISSUE TITLE
How to use multiple directories by OpenCppCoverage

### ISSUE THREAD

**Issue by soonsolidchentuo** [OpenCppCoverage/OpenCppCoverage#134]
I need to not contain multiple source file directories. What is the writing format?
The following format seem to don't work：
opencppcoverage --sources [source directory] --excluded_sources [exclude sources dir1] [exclude sources dir2] -- Test.exe

**Comment by WimLeflere** [comment]
From the [command line reference](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Command-line-reference):
`--excluded_sources arg The pattern that source's paths should NOT match. Can have multiple occurrences.`

So you have to repeat the command line argument for multiple directories.
E.g. `opencppcoverage --sources [source directory] --excluded_sources [exclude sources dir1] --excluded_sources [exclude sources dir2] -- Test.exe`

**Comment by soonsolidchentuo** [comment]
Thanks very much.
