### ISSUE TITLE
How to use with GitHub actions

### ISSUE THREAD

**Issue by amir9480** [OpenCppCoverage/OpenCppCoverage#135]
Hello.

How to use OpenCppCoverage via Github actions for CI and upload coverage result to services like
[codecov](https://codecov.io/), [scrutinizer-ci](https://scrutinizer-ci.com/) or ... ?

As OpenCppCoverage doesn't have a standalone portable version I am confused about how should I use it on Github actions.

**Comment by WimLeflere** [comment]
You can execute OpenCppCoverage as a standalone command line tool ([CLI reference](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Command-line-reference)).
Which you can integrate in a CI workflow.
Howto for Jenkins: https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Jenkins

OpenCppCoverage has multiple output formats, you should check which format is accepted by the coverage service.

**Comment by pavelkryukov** [comment]
I upload report to Codecov with following procedure:

https://github.com/MIPT-ILab/mipt-mips/blob/966a028dfa299547e7f701a72609332224e2a4eb/.github/workflows/simulator.yml#L225-L253

The key points are:
1. Install the tools with choco: `choco install opencppcoverage codecov`
2. Invoke with XML output: `call "C:\Program Files\OpenCppCoverage\OpenCppCoverage.exe" --export_type cobertura:coverage.xml --modules "*.exe" --excluded_line_regex "\s*\}.*" -- .\build\Debug\unit-tests.exe`
3. Upload: `codecov -f coverage.xml --root .`

**Comment by amir9480** [comment]
@pavelkryukov  @WimLeflere 

This is exactly what I looking for.
https://github.com/MIPT-ILab/mipt-mips/blob/966a028dfa299547e7f701a72609332224e2a4eb/.github/workflows/simulator.yml#L237

Thanks for your answers.
