### ISSUE TITLE
Command line option to select output directory

### ISSUE THREAD

**Issue by Warwolt** [OpenCppCoverage/OpenCppCoverage#137]
**Is your feature request related to a problem? Please describe.**
When running the coverage tool, it would be helpful to be able to select where the generated files would be put.

**Describe the solution you'd like**
Add a command line switch `--output_dir` that takes a path to output generated files to.

**Comment by WimLeflere** [comment]
This can be done with the `--export_type` command line argument, see [CLI reference](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Command-line-reference).
```
--export_type arg (=html)         Format: <exportType>:<outputPath>.
                                    <exportType> can be: html, cobertura or
                                    binary
                                    <outputPath> (optional) export output path.
                                    Must be a folder for html and a file for
                                    cobertura or binary.
                                    Example: html:MyFolder\MySubFolder
```

**Comment by Warwolt** [comment]
That seems like it's a little hidden, but never the less it seems like the option is there.
