### ISSUE TITLE
Cobertura report: filename attribute is missing the Windows Drive letter

### ISSUE THREAD

**Issue by zosrothko** [OpenCppCoverage/OpenCppCoverage#14]
## Describe your environment
- Version of OpenCppCoverage: 0.9.6.1
- Architecture (x86/ x64): x86
- Windows version: 10

## Describe your problem
With the Cobertura export, the filename attribute is missing the Windows Drive letter
```
<?xml version="1.0" encoding="utf-8"?>
<coverage line-rate="0.28391903337885255" branch-rate="0" complexity="0" branches-covered="0" branches-valid="0" timestamp="0" lines-covered="0" lines-valid="0" version="0">
  <sources>
    <source>c:</source>
    <source>f:</source>
  </sources>
  <packages>
    <package name="C:\Users\fandre\Documents\git\feature-gradle\bin\PocoCppUnitd.dll" line-rate="0.58553127354935941" branch-rate="0" complexity="0">
      <classes>
        <class name="iomanip" filename="program files (x86)\microsoft visual studio 14.0\vc\include\iomanip" line-rate="0" branch-rate="0" complexity="0">
          <methods/>
          <lines>
            <line number="526" hits="0"/>
            <line number="527" hits="0"/>
            <line number="528" hits="0"/>
            <line number="529" hits="0"/>
          </lines>
        </class>
        <class name="iosfwd" filename="program files (x86)\microsoft visual studio 14.0\vc\include\iosfwd" line-rate="0.40909090909090912" branch-rate="0" complexity="0">

```
## Attached file
[LastCoverageResults.log](https://github.com/OpenCppCoverage/OpenCppCoverage/files/1464363/LastCoverageResults.log)

**Comment by OpenCppCoverage** [comment]
Hello,

Sorry for my late answer.
Strangely, this is the Cobertura format. If you put the drive letter for class filename then you cannot display the report in Jenkins for example.
See [here](https://raw.githubusercontent.com/jenkinsci/cobertura-plugin/master/src/test/resources/hudson/plugins/cobertura/coverage-with-data.xml) for another example

I hope it will help,

OpenCppCoverage

**Comment by mladenmilev** [comment]
@zosrothko Hi,

I just successfully integrated OpenCppCoverage with Google Tests and Cobertura xml report in Jenkins. All the sources are well visible. I would not care for the actualy xml structure unless you need to parse it manually. 

Cobertura plugin for Jenkins has no issue with it.

I think this thread can be closed or put into FAQ.

**Comment by zosrothko** [comment]
That's ok. I will never read the xml report. Was just a surprising design for me.
