### ISSUE TITLE
Can OpenCppCoverage support a background process coverage?

### ISSUE THREAD

**Issue by theRealRed** [OpenCppCoverage/OpenCppCoverage#15]
Hi.

There is a situation that I want to do a functional test to a background process, like a server-side program. This myserver.exe is running all the time in background and won't exit by itself. I make a myclienttest.exe to communicate with this myserver.exe and functional test it. Can I run myserver.exe in background by OpenCppCoverage and run myclienttest.exe normally to execute a series of functional testing, and OpenCppCoverage collect the coverage? 

I think OpenCppCoverage can collect code coverage at runtime, but it seems only when the program exits, the coverage data can be dumped to a file. Is there any way to dump the coverage data at runtime or like gcov, provide a signal-handler in OpenCppCoverage to dump the data when a ctrl-c or a kill signal being captured?

Looking forward to your answer.

**Comment by OpenCppCoverage** [comment]
Hello,

You need to wait for the end of the program to have the coverage.
I have added a section [here](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Roadmap#dump-the-code-coverage-when-the-program-is-running) in _Community feature requests_ (low priority).

I hope it will help,

OpenCppCoverage

**Comment by theRealRed** [comment]
Thank you, hope it can go live soon later. It would be very helpful for back-end functional/system testing. OCC works perfect with gtest for my unit testing now.

**Comment by OpenCppCoverage** [comment]
Hello,

There is a low priority that this feature will be added! If you really need it, I suggest implementing it. I can give you some explanation on how to implement a simplified version of this feature that can feet your needs.

I hope it will help,

OpenCppCoverage

**Comment by delsner** [comment]
I would be interested in implementing this feature, i.e. a `DumpCoverage(filename)` function, to dump coverage to a specific file at runtime.
My use case is that I want to obtain *coverage-per-test-case* which is related to #56 as well.
Hence, I would like to use Google Test's [EventListeners API](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#defining-event-listeners) (e.g. `OnTestEnd(...)`) together with this `DumpCoverage()` function.

Could you give the explanation you mentioned above for a simple implementation?

Thanks in advance.

**Comment by OpenCppCoverage** [comment]
See https://github.com/OpenCppCoverage/OpenCppCoverage/issues/110.
