### ISSUE TITLE
Please verify the syntax export_type=cobertura:<path> works as described in documentation

### ISSUE THREAD

**Issue by mladenmilev** [OpenCppCoverage/OpenCppCoverage#16]
## Describe your environment
- Version of OpenCppCoverage: 0.9.6.1
- Architecture (x86/ x64): x64
- Windows version: 7 Enterprise

## Describe your problem
Steps to reproduce:
1. create config.txt file
2. _in the config.txt file define `export_type=cobertura:UnitTest\`  or `export_type=cobertura:UnitTest` or `export_type=cobertura:\UnitTest\` . All 3 variants were experiemented one by one trying to define a path relative to current path of executing opencppcovenrage.
3. Run `OpenCppCoverage.exe --config_file="config.txt" -- "UnitTests\Debug\UnitTests.exe" --gtest_output="xml:UnitTests\UnitTests.xml"` 

wherein the `gtest_output="xml:UnitTests\UnitTests.xml"` are arguments to the tests defining output file . 
`UnitTestCobertura.xml` files is **NOT** generated. **NOT OK**
Result of test execution by gtest defined by gtest_output argument above **IS** generated OK.
Following error is printed by opencppcobertura when trying write file (via Jenkins and CMD command)

`Error: <unspecified file>: write error`

Please verify the syntax `export_type=cobertura:<path>`  works as described in https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Command-line-reference  

> Format: \<exportType\>:\<outputPath\>.
>                                    \<exportType\> can be: binary, cobertura, html
>                                    \<outputPath\> (optional) output file or
>                                    directory for the export.
>                                    Example: html:MyFolder\MySubFolder
>                                    This flag can have multiple occurrences.

This functionality is usable as it allows the config file to be placed in different location from the output coverage files. By specifying a path helps having single config.txt file and calling opencppcoverage multiple times with diffirent arguments for UnitTest.exe producing several UnitTestCobertura.xml files, later imported in Jenkins.

I am not sharing the verbose log but only the normal Jenkins. If required will log verbosely

```
18:25:05 C:\Program Files (x86)\Jenkins\jobs\integration_(master)\workspace>OpenCppCoverage.exe --config_file="C:\Program Files (x86)\Jenkins\jobs\integration_(master)\workspace\opencppcoverage_config.txt" -- "C:\Program Files (x86)\Jenkins\jobs\integration_(master)\workspace\UnitTests\Debug\UnitTests.exe" --gtest_output="xml:UnitTests\UnitTests.xml" 
18:25:05 [==========] Running 0 tests from 0 test cases.
18:25:05 [==========] 0 tests from 0 test cases ran. (1 ms total)
18:25:05 [  PASSED  ] 0 tests.
18:25:05 [info] Start Program:
18:25:05 Path:"C:\Program Files (x86)\Jenkins\jobs\integration_(master)\workspace\UnitTests\Debug\UnitTests.exe"
18:25:05 Arguments:--gtest_output=xml:UnitTests\UnitTests.xml 
18:25:05 Working directory: not set.
18:25:05 Modules: Selected: workspace\****masked propriatory****\Debug\ workspace\****masked propriatory****\Debug\ workspace\****masked****\Debug\ workspace\****masked****\Debug\ workspace\****masked propriatory****\Debug\ workspace\****masked****\Debug\ workspace\****masked****\Debug\ workspace\****masked propriatory****\Debug\ workspace\****masked propriatory****\Debug\ workspace\****masked propriatory****\Debug\ workspace\UnitTests\Debug\ Excluded: workspace\dist\ workspace\ExternalLibs\ workspace\UnitTests\Debug\zip.dll workspace\UnitTests\Debug\zlib1.dll workspace\UnitTests\Debug\tinyxml2.dll 
18:25:05 Sources: Selected: workspace\****masked propriatory****\ workspace\****masked propriatory****\ workspace\****masked propriatory****\ workspace\****masked propriatory****\ workspace\utilities\ workspace\****masked propriatory****\ workspace\****masked propriatory****\ workspace\****masked propriatory****\ workspace\****masked propriatory****\ workspace\****masked propriatory****\ Excluded: 
18:25:05 Log Level: Normal
18:25:05 Cover Children: 0
18:25:05 Aggregate by file: 1
18:25:05 Continue after C++ exception: 0
18:25:05 Optimized build support: 0
18:25:05 Export: Cobertura UnitTests 
18:25:05 Input coverage: 
18:25:05 Unified diff: 
18:25:05 Excluded line regular expressions: 
18:25:05 
18:25:05 [info] Module: C:\Program Files (x86)\Jenkins\jobs\integration_(master)\workspace\UnitTests\Debug\UnitTests.exe is selected because it matches selected pattern: workspace\UnitTests\Debug\
18:25:05 [info] Module: C:\Windows\System32\ntdll.dll is skipped because it matches no selected patterns
18:25:05 [info] Module: C:\Windows\SysWOW64\ntdll.dll is skipped because it matches no selected patterns
18:25:05 [info] Module: C:\Windows\System32\wow64.dll is skipped because it matches no selected patterns
18:25:05 [info] Module: C:\Windows\System32\wow64win.dll is skipped because it matches no selected patterns
18:25:05 [info] Module: C:\Windows\System32\wow64cpu.dll is skipped because it matches no selected patterns
18:25:05 [info] Module: C:\Windows\System32\kernel32.dll is skipped because it matches no selected patterns
18:25:05 [info] Module: C:\Windows\SysWOW64\kernel32.dll is skipped because it matches no selected patterns
18:25:05 [info] Module: C:\Windows\System32\kernel32.dll is skipped because it matches no selected patterns
18:25:05 [info] Module: C:\Windows\System32\user32.dll is skipped because it matches no selected patterns
18:25:05 [info] Module: C:\Windows\SysWOW64\kernel32.dll is skipped because it matches no selected patterns
18:25:05 [info] Module: C:\Windows\SysWOW64\KernelBase.dll is skipped because it matches no selected patterns
18:25:05 [info] Module: C:\Windows\SysWOW64\msvcp120d.dll is skipped because it matches no selected patterns
18:25:05 [info] Module: C:\Windows\SysWOW64\msvcr120d.dll is skipped because it matches no selected patterns
18:25:05 Error: <unspecified file>: write error 
```

**Comment by OpenCppCoverage** [comment]
Hello,

Thank you very much for the detailed report.
For HTML, you must specify a folder but for cobertura and binary exports, you must specify a file.
I will update the documentation and provide a better error message in the next release.

I hope it will help,

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

The error message is improved in [OpenCppCoverage 0.9.7.0](https://github.com/OpenCppCoverage/OpenCppCoverage/releases/tag/release-0.9.7.0) and the documentation is updated.

OpenCppCoverage
