### ISSUE TITLE
Consider normalizing paths for --sources (and --modules)

### ISSUE THREAD

**Issue by horenmar** [OpenCppCoverage/OpenCppCoverage#17]
OpenCppCoverage is currently sensitive to differences between '\' and '/' in `--sources`  arguments.

This means that called like this 
`OpenCppCoverage --export_type cobertura --quiet --sources C:\projects\Catch2 -- C:\projects\Catch2\Build\Debug\SelfTest.exe`
will result in the expected report, but this 
`OpenCppCoverage --export_type cobertura --quiet --sources C:/projects/Catch2 -- C:/projects/Catch2/Build/Debug/SelfTest.exe`
will run the SelfTest, but filter out everything, creating an empty report.

I ran into this when I was integrating OpenCppCoverage with our project's CI on AppVeyor. Since we use CMake and CTest I had to redirect CTest and it provides the target path using forward slashes... this meant that I ended up with the tests providing proper output, but empty files, which took awhile to diagnose.

_This probably also applies to `--modules`_

Tested with v 0.9.6.1 release.

**Comment by OpenCppCoverage** [comment]
Hello,

Unfortunately, this is a very common pitfall. 
_--sources_ and _--modules_ accept patterns and not paths. For example, ``--sources Pr*ject*`` is a valid option. A full path works as long as it match exactly the full path in the pdb.

I will make the documentation more explicit about it.
I am also going to add a warning in the next release.

I hope it will help,

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

The error messages are improved in [OpenCppCoverage 0.9.7.0](https://github.com/OpenCppCoverage/OpenCppCoverage/releases/tag/release-0.9.7.0) and the documentation was updated.

OpenCppCoverage
