### ISSUE TITLE
Allow user to ignore previous exit codes when merging

### ISSUE THREAD

**Issue by horenmar** [OpenCppCoverage/OpenCppCoverage#18]
I want to use OpenCppCoverage to merge several of its outputs into single cobertura xml to use later. However, some of the previous runs exited with non-zero return value, so this call
```
OpenCppCoverage --input_coverage=cov-report1.bin --input_coverage=cov-report2.bin --input_coverage=cov-report3.bin --input_coverage=cov-report4.bin --input_coverage=cov-report5.bin --input_coverage=cov-report6.bin --export_type cobertura:cobertura.xml
```
also exits with a non-zero value, breaking CI build in the process. I can work around it easily enough, but would still a command-line switch that would tell OpenCppCoverage not to return the highest return value from inputs.

**Comment by OpenCppCoverage** [comment]
Hello,

Some users would like to know when a test failed and that explain the current behaviour.
I would like to avoid adding a new flag when there is an easy work around and so do not plan for now to add it.

OpenCppCoverage

**Comment by horenmar** [comment]
A counter-argument: They will already know, because it has already failed for the input report to be generated.

To explain, consider this sequence of steps

1) Test A is ran: `OpenCppCoverage -- test-binary-A.exe` and it passes
2) Test B is ran: `OpenCppCoverage -- test-binary-B.exe` and it fails with return code 2
3) Test C is ran: `OpenCppCoverage -- test-binary-C.exe`
4) Use wants to merge coverage from tests A-C.

Any competent test runner will already report that Test B failed during step 2. On the other hand, if step 4 returns step 2's error code, then it looks like the error occured during the merge, rather than at some ill-defined point in the past.

**Comment by OpenCppCoverage** [comment]
Hello,

Thanks for your feedback. This behavior is changed in master branch.

OpenCppCoverage.

**Comment by OpenCppCoverage** [comment]
Hello,

It is availabe in [OpenCppCoverage 0.9.7.0](https://github.com/OpenCppCoverage/OpenCppCoverage/releases/tag/release-0.9.7.0).

OpenCppCoverage

**Comment by FlorianWolters** [comment]
Hello,

no matter what I've tried, I couldn't convince OpenCppCoverage to ignore the exit code of the executable / do not forward it to the caller. I am currently integrating OpenCppCoverage in my CMake-based build system (with `add_custom_target`). I have one `[...]_cov` custom target for each test executable and one custom target that runs all `[...]_cov` and aggregates the binary reports. Therefore a `[...]_cov` target has to return `0` **always**. I've not been able to ignore the exit code without a wrapper script first, which was overly complicated and clumsy imo.

The following prints `Exit Code is 0` if executed in a `cmd.exe`:

    OpenCppCoverage ^
    --quiet ^
    --sources app ^
    --sources include ^
    --sources src ^
    --export_type binary:foo.cov ^
    --continue_after_cpp_exception ^
    -- foo.exe ^
    --gtest_shuffle ^
    --gtest_color=no ^
    --gtest_print_time=0 ^
    > nul 2>&1
    echo Exit Code is %errorlevel%

My current working approach in CMake looks as follows:

    add_custom_target(${test_coverage_target_name}
        ${OpenCppCoverage_EXECUTABLE}
        --quiet
        ${opencppcoverage_sources_args}
        --export_type html:${html_output_dir_path}
        --export_type cobertura:${cobertura_output_file_path}
        --export_type binary:${binary_output_file_path}
        --continue_after_cpp_exception
        -- $<TARGET_FILE:${test_target_name}>
        --gtest_shuffle
        --gtest_color=no
        --gtest_print_time=0
        --gtest_output=xml:${CMAKE_CURRENT_BINARY_DIR}/OpenCppCoverage/${test_target_name}_test_detail.xml
        # Ignore the exit code of OpenCppCoverage.
        > nul 2>&1 & set ERRORLEVEL=0
      BYPRODUCTS
        ${html_output_dir_path}
        ${cobertura_output_file_path}
        ${binary_output_file_path}
      # Attention: Do not use the `VERBATIM` option, otherwise the exit code is not ignored.
      )

So it only works if using the os-specific `> nul 2>&1 & set ERRORLEVEL=0` and omitting the `VERBATIM` option.

Is this a regression? In the last response it has been stated that the behavior as been changed. Let me suggest a `--no-exit-code-forward` (bad name) CLI option. Then the user can decide and hacks like mine are not longer necessary.

Returning `0` seems mandatory in a use case like mine and I think it generally makes sense for build system integration. The task of the test runner is to run the tests and to report the aggregated result to the caller. The task of the coverage tool is collecting coverage data. Only if that fails, the coverage tool should return an error, imo (e.g. bad CLI flags, missing input files, etc.).

Great project, btw!

**Comment by OpenCppCoverage** [comment]
Hello,

Sorry for my late answer.
OpenCppCoverage returns the program exit code (or 0x9F8C8E5C if OpenCppCoverage failed).

I understand your use case but it looks like to be not related to OpenCppCoverage. You have the same issue with GTest and CMake without OpenCppCoverage.

You can returns 0 from your GTest main function for example.
This [link](https://stackoverflow.com/questions/50027063/cmake-ignore-return-on-custom-target) can also help, if you do not want to update your code.

Let me know if I misunderstood your problem or if my answer helps.

OpenCppCoverage
