### ISSUE TITLE
can't run in cmd

### ISSUE THREAD

**Issue by superxiaov** [OpenCppCoverage/OpenCppCoverage#19]
**Before creating an issue, please make sure the answer is not in the [FAQ](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ).**

**This template is applied for all bug requests. Remove it for other general question or feature request.**

## Describe your environment
- Version of OpenCppCoverage: ___lastest__
- Architecture (x86/ x64): _x64____
- Windows version: ____win10 _

## Describe your problem
when i setup the software . i can't run it in cmd line.i have set it in Path envirement.

Could you reproduce the issue on a toy example?

## Attached file
Attach the log file *LastCoverageResults.log*, located in your current folder.

If the report does not contain the expected files, please run OpenCppCoverage with ```--verbose``` flag. This will add more information into *LastCoverageResults.log*.

**Comment by OpenCppCoverage** [comment]
Hello,

What do you mean by ```when i setup the software```?
``i can't run it in cmd line``: Is there any error message?
What is exactly your problem, during the installation or during the execution?

Can you provide LastCoverageResults.log?

OpenCppCoverage

**Comment by superxiaov** [comment]
I have resolved  the problem. I think it happened by my fault.so sorry
