### ISSUE TITLE
Plans to support branch coverage?

### ISSUE THREAD

**Issue by Resurr3ction** [OpenCppCoverage/OpenCppCoverage#20]
The question/request is in the title. Do you plan to support branch coverage as well? Line coverage is useful  for general overview of the code coverage however branch coverage tells more about what exactly (which code paths) is being tested and what is not.

**Comment by OpenCppCoverage** [comment]
Hello,

Branch coverage is not planned. Let me know if you want to work on it (It could be a plugin),

I hope it will help,

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

I am closing this issue as it is not active anymore. Feel free to open a new issue if you would like more information on this topic.

OpenCppCoverage

**Comment by berryzplus** [comment]
Hello.

I have some questions.

> Branch coverage is not planned. Let me know if you want to work on it (It could be a plugin),

1. It seems that [the data definition of the plugin's](https://github.com/OpenCppCoverage/OpenCppCoverage/blob/master/Plugin/Exporter/LineCoverage.hpp) is not possible to implement branch coverage.  
Do you say I can change it, including improving the plugin data structure?
1. Is there any documentation about how to make a plugin?  
Maybe I can customize the code, I care about your "rules".
1. Why don't you plan branch coverage?
It seemed to say "I will never do it". Why do you say so much?

**Comment by berryzplus** [comment]
sorry, my issue bas been self resolved.
https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Plugin-usage
