### ISSUE TITLE
any way to get the coverage from a thirdparty DLL only with the DLL's pdb file?

### ISSUE THREAD

**Issue by superxiaov** [OpenCppCoverage/OpenCppCoverage#21]
hi sir
     My work is testing the DLL from the other development department.As the security rule I can't get the code.So my question is how can I get the coverage due to the conditions.
     Now I have my testcode.exe and then i also get the coverage for my testcode.exe.But in the test project I add the DLL what I want to test  it seems like no coverage. I also use the opencppcoverage plugin but the same result.
     The test DLL  I have no method to compline it.The pdb for it  I can get .Is there any way to resolve it?
![result](https://user-images.githubusercontent.com/25789546/34345027-ba31ae16-ea26-11e7-9a4d-4c37a0ffdc7e.PNG)
![vs2015 plugin](https://user-images.githubusercontent.com/25789546/34345028-ba6701ce-ea26-11e7-97c9-759f0413f253.PNG)

**Comment by ogaca-planorama** [comment]
Hello,

OpenCppCoverage plugin restricts source files to existing projects so you also need to fill ``Additional source Pattern`` with something that matchs the path of your source files for your dll. In doubt, you can use ``*`` as value for ``Additional source Pattern`` to have all sources.

Please let me know if it solves your problem.

I hope it will help,

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

OpenCppCoverage plugin restricts source files to existing projects so you also need to fill ``Additional source Pattern`` with something that matchs the path of your source files for your dll. In doubt, you can use ``*`` as value for ``Additional source Pattern`` to have all sources.

Please let me know if it solves your problem.

I hope it will help,

OpenCppCoverage

**Comment by superxiaov** [comment]
OK.So OpenCppCoverage comand line also need to fill the dll's source files then it can works well .Right?

**Comment by OpenCppCoverage** [comment]
Hello,

OpenCppCoverage needs to know which files to consider and which files to exclude. More information can be found at https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Command-line-reference#--sources-arg and https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Command-line-reference#--modules-arg.

Note: In the _Command line_ tab in your screenshot, you can see all parameters passed to OpenCppCoverage.exe.

I hope it will help,

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

I am closing this issue as it is not active anymore. Feel free to open a new issue if my last comment did help you.

OpenCppCoverage
