### ISSUE TITLE
Cannot write to binary file

### ISSUE THREAD

**Issue by bert8128** [OpenCppCoverage/OpenCppCoverage#23]
## Describe your environment
- Version of OpenCppCoverage: 0.9.6.1
- Architecture (x86/ x64): x64
- Windows version: 7

## Describe your problem
Steps to reproduce:
1. Run OpenCppCoverage with a particular config with html output.  This produces a sensible result.
2. Run OpenCppCoverage with a particular config with bianry output.  This produces an eror message after running the program "Error: c:\program files (x86)\jenkins\workspace\opencppcoverage\exporter\binary\coveragedataserializer.cpp:87 Cannot serialize message to stream"

Command line was:
C:\Users\bertie.smith\Downloads>"C:\USERS\BERTIE.SMITH\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_84EE4AEF\EXTENSIONS\SNOGWFNY.XH3\OpenCppCoverage-x64\OpenCppCoverage.exe" --export_type "html:c:tmpFiles\codeCov" --verbose --sources * --modules * --working_dir "D:\Projects\Projects\Apex2015\Dev\cpp\Src\Test\TestFramework\\"  --plugin  -- "D:\Projects\Projects\Apex2015\Dev\cpp\Src\Test\TestFramework\../../../bin64\TestFrameworkd.exe" -offline

Bad result from binary run:
[LastCoverageResults.log](https://github.com/OpenCppCoverage/OpenCppCoverage/files/1673013/LastCoverageResults.log)
Good result from html run:
[LastCoverageResults_HTML.log](https://github.com/OpenCppCoverage/OpenCppCoverage/files/1673015/LastCoverageResults_HTML.log)

**Comment by OpenCppCoverage** [comment]
Hello,

It looks like you had ``--export_type=binary:c:\tmpFiles\codeCov`` where ``codeCov`` is an existing folder.
It is the same issue as https://github.com/OpenCppCoverage/OpenCppCoverage/issues/16.

I hope it will help,

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

Error message improved in [OpenCppCoverage 0.9.7.0](https://github.com/OpenCppCoverage/OpenCppCoverage/releases/tag/release-0.9.7.0).

OpenCppCoverage
