### ISSUE TITLE
Consider making output HTML more compact

### ISSUE THREAD

**Issue by bert8128** [OpenCppCoverage/OpenCppCoverage#24]
Currently the generated HTML results file of summary by file is quite low density.  Becuase of the pie charts (nice as they are) you don't see many files on the screen at any one time.  It would be nice if there were an option to just have a textual output only with three columns: file name (with path), number of coverable lines, number of lines covered.

**Comment by OpenCppCoverage** [comment]
Hello,

First, I am sorry for my late answer.
I have just added a new entry in the FAQ that can interesting you: [More report formats](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ#more-report-formats).

I hope it will help,

OpenCppCoverage

**Comment by bert8128** [comment]
I seriously think you need to revisit this option.  Whilst I agree that in the end something more sophisticated is required for large projects, it's difficult to test when you have 10s of 1000s of source files - the output html file is just too big with all the pie charts - it takes ages to render.  It would be very usefult to have an option in the HTML generation to not generate the pie charts.
For large projects, it would be faster to generate, faster to view, and be more useful all round.
PS - we are already using the OpenCppCoverage with the plugin in Visual Studio, and with Jenkins across the whole project, so understand that I am not being negative - I think it is a great tool.  I just think it could be greater.
