### ISSUE TITLE
Warning: line does not exist

### ISSUE THREAD

**Issue by bert8128** [OpenCppCoverage/OpenCppCoverage#25]
## Describe your environment
- Version of OpenCppCoverage: 0.9.6.1
- Architecture (x86/ x64): x64
- Windows version: 7

## Describe your problem
Steps to reproduce:
1. Run coverage against a large project.  Some files cause the following warning to be generated:
[warning] <afile.cpp> line <aline> does not exist, skipped
It is not clear what the cause of the warning is, nor how to fix it.  It only appears for a few files, but can appear multiple times.  The number of timevaries between 1 and 9 in my particular scenario.
Log file attached.  RUnning with --verbose does not produce any extra 
[LastCoverageResults.log](https://github.com/OpenCppCoverage/OpenCppCoverage/files/1673139/LastCoverageResults.log)
output which relates to this issue.

**Comment by OpenCppCoverage** [comment]
Hello,

You can safely ignore this warning and I already removed it on the master branch.
It happens when Visual Studio generates some code at a line which is greater than the number of line in the file.

I hope it will help,

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

This warning is removed in [OpenCppCoverage 0.9.7.0](https://github.com/OpenCppCoverage/OpenCppCoverage/releases/tag/release-0.9.7.0).

OpenCppCoverage
