### ISSUE TITLE
Missing files in the report

### ISSUE THREAD

**Issue by epot** [OpenCppCoverage/OpenCppCoverage#27]
Maybe I am missing the point, but my issue is different than the one described in the FAQ. My library consists of many files, but only some of them are displayed in the report and taken into account to calculate the coverage. Is it because I am "including" them somehow in the tests? Is there a way to automatically include all my sources?

I am running in Windows 10 x64 with Visual Studio 2017.

**Comment by OpenCppCoverage** [comment]
Hello,

I am assuming you use OpenCppCoverage command line (not the plugin).
Can you try without any ``--modules`` and ``--sources`` flag?
 
I hope it will help,

OpenCppCoverage

**Comment by epot** [comment]
Yes indeed! I tried without those options but I do not get more files from my source code. Maybe the Visual studio linker is doing some optimizations and is removing the symbols not used in my tests?

**Comment by epot** [comment]
I think I found the flag, it is much better with "/OPT:NOREF"!
