### ISSUE TITLE
Does OpenCppCoverage use _NT_SYMBOL_PATH?

### ISSUE THREAD

**Issue by amai2012** [OpenCppCoverage/OpenCppCoverage#29]
Does OpenCppCoverage use _NT_SYMBOL_PATH (see https://msdn.microsoft.com/en-us/library/windows/desktop/ee416588(v=vs.85).aspx)?

**Comment by OpenCppCoverage** [comment]
Hello,

First, I am sorry for my late answer. I spent a lot of time updating the code but at the end the solution is quite easy.

You need to copy the file ``SymSrv.dll`` into OpenCppCoverage installation folder (where ``OpenCppCoverage.exe`` is located). Be careful about the difference between x86 and x64 versions.

First, install [Debugging tools for Windows](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/)
``SymSrv.dll`` will be available in the folder ``C:\Program Files (x86)\Windows Kits\10\Debuggers\x64`` or ``C:\Program Files (x86)\Windows Kits\10\Debuggers\x86``.

I hope it will help,

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

Feel free to open a new issue if you still have a problem.

OpenCppCoverage
