### ISSUE TITLE
Support forward slash in paths

### ISSUE THREAD

**Issue by amai2012** [OpenCppCoverage/OpenCppCoverage#30]
Working with ant and other portable scripts it's sometimes difficult to get the paths separator right. It would be convenient if OpenCppCoverage accept forward slashes `/` in paths as well.

**Comment by OpenCppCoverage** [comment]
Hello,

I make the error messages for ``/`` more explicit in the next release, .
In your case, creating a bat file should solve your problem

```
set arg1=%1

REM Replace / by \
set source=%arg1:/=\%

OpenCppCoverage --sources %source% -- YOUR_PROGRAM.exe
```
 
See https://www.dostips.com/DtTipsStringManipulation.php#Snippets.Replace for DOS string manipulation.

I hope it will help,

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

Please open a new discussion if you need more information.

OpenCppCoverage
