### ISSUE TITLE
Working dir functionality question

### ISSUE THREAD

**Issue by ChasM2** [OpenCppCoverage/OpenCppCoverage#32]
Hi,

How can I change the working directory in the config? it seems that working_dir doesn't work.
I have the following config:
`working_dir=c:\dev\RepName
sources=Sources
export_type=cobertura
export_type=html
excluded_sources=UnitTests
excluded_sources=GeneratedFiles`

I change working _dir option according to my repo but it is always the same - "c:" - see screenshot
![c__dev_unittestscoverage xml - notepad 2018-02-20 16 02 02](https://user-images.githubusercontent.com/3586216/36425335-88da762e-1657-11e8-847d-cfebf996c250.jpg)

Would you please help me ?

**Comment by OpenCppCoverage** [comment]
Hello,

First, I am sorry for my late answer.
I have just tested ``--working_dir`` with ``--config_file`` and everything works fine.

``--working_dir`` defines the current folder for the program executed. Your screenshot shows a Cobertura export (An external format not defined by OpenCppCoverage). There is no link between the two options.  

I hope it will help,

OpenCppCoverage

**Comment by ChasM2** [comment]
Thank you for the answer.
