### ISSUE TITLE
Sort HTML page by columns

### ISSUE THREAD

**Issue by amai2012** [OpenCppCoverage/OpenCppCoverage#34]
The main HTML page could be made sortable, i.e. currently by

- coverage
- lines
- items

**Comment by OpenCppCoverage** [comment]
Hello,

I added a few days ago [More report formats](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ#more-report-formats) in the FAQ.
Maybe it can help,

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

For now, I do not plan to make important changes to the HTML report and so ReportGenerator may fit the need for some users.

OpenCppCoverage
