### ISSUE TITLE
Module shown twice in HTML report (with and w/o full path)

### ISSUE THREAD

**Issue by amai2012** [OpenCppCoverage/OpenCppCoverage#35]
## Describe your environment
- Version of OpenCppCoverage: 0.9.7.0
- Architecture (x86/ x64): x64
- Windows version: 7

## Describe your problem
Steps to reproduce:
1. Run on c:\foo\test.exe which is not in PATH
2. View HTML. It shows test.exe in addition to c:\foo\test.exe
3. _______________

**Comment by OpenCppCoverage** [comment]
Hello,

Thank you for reporting this issue. 
The first line is the sum for all modules and the second line is the single module. (See https://github.com/OpenCppCoverage/OpenCppCoverage/issues/12). 
Displaying the sum for all modules only make sense when there are several modules.

OpenCppCoverage

**Comment by amai2012** [comment]
I see.
Confusing IMHO.
