### ISSUE TITLE
Version OpenCppCoverage 0.9.7.0 does not find any source files

### ISSUE THREAD

**Issue by paulomotta** [OpenCppCoverage/OpenCppCoverage#36]
## Describe your environment
- Version of OpenCppCoverage: 0.9.7.0
- Architecture (x86/ x64): x64
- Windows version: Win7

## Describe your problem
Steps to reproduce:
1. Compiled my project using CMake and the command line tools of MSVC 19.0.23026.0
2. Tried both with and without Ninja so it probably does not affect the result
3. Moved to the build folder (the pdbs are located there together with the application)
4. Executed the application with all the possible configurations listed on the documentation
5. The application runs successfully, many [debug] messages are shown
6. The HTML contains no reference to the source files that should be listed

I've opened the .pdb and verified the source code location, so the substitute_pdb_source_path is not necessary

Could you reproduce the issue on a toy example?
I am using a simple application to try the coverage tool for later incorporating it in our build pipeline

**Comment by paulomotta** [comment]
Removed the version 0.9.7.0 and tested 0.9.6.1. Although it is slower, it worked fine.

**Comment by OpenCppCoverage** [comment]
Hello,

Thank you for reporting this issue.
Could you post the log files (with --verbose if possible) for the version 0.9.7.0 and 0.9.6.1 with the same command line?
It will help me fix the issue in 0.9.7.0 version.

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

I am closing this issue. Feel free to create a new one if you have more information.

OpenCppCoverage.
