### ISSUE TITLE
About License of usage of this tool.

### ISSUE THREAD

**Issue by taeguk** [OpenCppCoverage/OpenCppCoverage#37]
The license of source code is GPL.
How about the usage of this tool? 
Isn't the usage of this tool under GPL?
Can I use this tool for commercial purpose without any restrictions?
Thank you.

**Comment by OpenCppCoverage** [comment]
Hello,

You can use OpenCppCoverage to compute the code coverage when developing a commercial application without restrictions.
Does it answer to your question? If not, can you give more detail?

I hope it will help,

OpenCppCoverage

**Comment by taeguk** [comment]
@OpenCppCoverage It's clear. Thank you! 👍
