### ISSUE TITLE
Include source code paths that are not present in .exe's .pdb files

### ISSUE THREAD

**Issue by lboulougaris** [OpenCppCoverage/OpenCppCoverage#38]
Hello,

We work on a project with multiple libraries, static and dynamic. We have only written unittests for one of them. We want to use the OpenCppCoverage to generate a coverage report for all the sources in the project.

Our issue is that OpenCppCoverage finds the source code files under test through the .pdb files generated for the unittests executable. As a result, OpenCppCoverage will only generate report for those files, and not the other files of the project.

**What if OpenCppCoverage could accept a include_sources_dir argument where someone could specify a directory with source files that OpenCppCoverage would generate report for?**

Another option would be to pass extra .pdb files that are not related with unittests executable.

Thanks in advance,
Leonidas

**Comment by OpenCppCoverage** [comment]
Hello,

``What if OpenCppCoverage could accept a include_sources_dir argument where someone could specify a directory with source files that OpenCppCoverage would generate report for?``
Now OpenCppCoverage uses pdb files to know which lines contain an instruction (OpenCppCoverage ignores empty lines and comments for example). This solution seems very complicated.

``Another option would be to pass extra .pdb files that are not related with unittests executable.``
I think it should be doable but it would require many code changes.

You can use the following workaround to force the load of your libraries:
 - For dynamic libraries, you can call [LoadLibrary](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684175(v=vs.85).aspx). For example ``LoadLibrary(L"Dll.dll");``
 - For static libraries, you can use the linker option [/WHOLEARCHIVE](https://msdn.microsoft.com/en-us/library/mt732963.aspx). For example ``/WHOLEARCHIVE:StaticLib``.

As you probably do not want to make these changes in your main program, I suggest creating a new project that only loads dynamic and static libraries as explained above. You can then merge the coverage of this new project with your initial project (See [here](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki#merging-coverage---input_coverage----export_typebinary)).

I hope it will help,

OpenCppCoverge

**Comment by adammarks** [comment]
We are seeing this same issue and are using the /WHOLEARCHIVE flag to get more of the source code included in coverage.  

Unfortunately using WHOLEARCHIVE causes all kinds of other linker issues including some about duplicate resources that are very difficult to work around.   I agree that your proposal of creating a new simplified project that only references and WHOLEARCHIVEs a library would probably help, but that is one more project to build/maintain.

Also it appears as though using WHOLEARCHIVE only seems to include .cpp files and not .h files. 

I think it would be nice to have a --include_sources arg   parameter that works just like --exclude_source arg  to force source files to be included.   

If you thought this might be something valuable to add I will probably start up a fork and try adding this functionality.

**Comment by adammarks** [comment]
@OpenCppCoverage  Reopening this issue as I see I added this comment to a closed issue so you may not have seen it
