### ISSUE TITLE
Header files are not set in coverage report

### ISSUE THREAD

**Issue by s-martin** [OpenCppCoverage/OpenCppCoverage#39]
## Describe your environment
- Version of OpenCppCoverage: 0.9.7
- Architecture (x86/ x64): x64
- Windows version: Windows 7

## Describe your problem
Steps to reproduce:
1. Run OpenCppCoverage for project which contains a couple of header-only files (suffix hpp)
2. Although tests for these header-only files were executed, coverage is marked as 0% for these header files

## Attached file
[LastCoverageResults.log](https://github.com/OpenCppCoverage/OpenCppCoverage/files/1825330/LastCoverageResults.log)

**Comment by OpenCppCoverage** [comment]
Hello,

As the code inside a header file exists only where it is compiled, you need to select the module where these files are used. In your case, you can try to add ``--modules F2ToolkitTest.exe`` to your command line.

I hope it will help,

OpenCppCoverage

**Comment by s-martin** [comment]
Thanks, I'll try that.

**Comment by s-martin** [comment]
It works, if I add the executable to the modules. Thanks.

Maybe it would be helpful to document that somewhere.
