### ISSUE TITLE
Question: does OpenCppCoverage provide method wise coverage?

### ISSUE THREAD

**Issue by majduddin** [OpenCppCoverage/OpenCppCoverage#4]
I can run the tool and see line by line coverage for given cpp file. But is it possible to see method wise coverage for the Classes?

Thanks, majd

**Comment by OpenCppCoverage** [comment]
Hello,

You cannot see the coverage by class or by method but only by file.
If you really need this feature please see [this discussion](https://opencppcoverage.codeplex.com/discussions/658102).

I hope it will help,

OpenCppCoverage
