### ISSUE TITLE
Improvement: Pass multiple values to options

### ISSUE THREAD

**Issue by s-martin** [OpenCppCoverage/OpenCppCoverage#42]
## Describe your environment
- Version of OpenCppCoverage: 0.9.7
- Architecture (x86/ x64): x64
- Windows version: Windows 7

## Describe your problem
It would be helpful, if multiple values (e.g. comma-separated) could be passed to an option.
Currently e.g. for multiple modules I have to use `--modules=MyDll.dll --modules=MyExecutable.exe`, which is not very intuitive. Same applies inside config files.

**Comment by amai2012** [comment]
You can have comma in filenames at least on Windows...
IMHO it's not worthwhile messing around with this while the functionality is available already.

**Comment by s-martin** [comment]
I'll try again for commas, thanks.

**Comment by amai2012** [comment]
>@amai2012 : Based on https://msdn.microsoft.com/en-us/library/aa365247 it seems coma ``,`` is not a reserved character. Do you have an example in mind? 

That's what I wanted to say! You can have a file named `a,b` and this would cause problems interpreting `--modules=MyDll.dll,YourDll.dll`
