### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by ericlemes** [OpenCppCoverage/OpenCppCoverage#45]
Hi there, I was looking in the Plugin repo, and you mention a Nuget package, which I couldn't find in Nuget repository. Is this a documentation bug or some problems publishing the package?

I'm integrating OpenCppCoverage in one of my projects, which I'm planning to use only for command line usage. Unfortunately I don't have a very easy way of deploying the binary. A NuGet package would be awesome for this. Do you have anything similar?

Thanks for the great tool.

**Comment by OpenCppCoverage** [comment]
Hello,

First, I am sorry for my late answer, I was working on another project :).

There is no Nuget package that bundle OpenCppCoverage.

There a Visual Studio plugin: https://github.com/OpenCppCoverage/OpenCppCoveragePlugin.

You can [build OpenCppCoverage from sources](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Building-OpenCppCoverage). Building third party libraries will create a Nuget package that contains only OpenCppCoverage dependencies.

I hope it will help,

OpenCppCoverage

**Comment by ericlemes** [comment]
So, I think a nuget package would be very useful, since in repos that uses OpenCppCoverage to get coverage data, won't be necessary to check in binaries. I have exactly this problem on one of my projects.

Would you be interested in getting a pull request if I contribute?

**Comment by OpenCppCoverage** [comment]
Hello,

I have noticed the Chocolatey package was updated: https://chocolatey.org/packages/opencppcoverage.
Does it help?

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

I am closing this issue as it is not active anymore. Feel free to reopen it or create a new one.

OpenCppCoverage.
