### ISSUE TITLE
Bad allocation in Jenkins job

### ISSUE THREAD

**Issue by dzolee** [OpenCppCoverage/OpenCppCoverage#47]
**Before creating an issue, please make sure the answer is not in the [FAQ](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ).**

**This template is applied for all bug requests. Remove it for other general question or feature request.**

## Describe your environment
- Version of OpenCppCoverage: 0.9.5.2
- Architecture (x86/ x64): x64
- Windows version: Win7

## Describe your problem
I run coverage for unit tests, from a Jenkins service on Windows.
Certain unit tests cause a "bad allocation" in OpenCppCoverage, just when trying to load the unit test EXE in question. There is no test code run at this point, it might be some global initialization in the test EXE, but I am clueless what it can be.

The same EXE can be profiled from the command line, without errors.
The same EXE can be profiled if I start a "service" command line with SysInternals PsExec.

The console output before the tool dies:
```
16:00:17 Starting vgl_simulation_matrix_ut.exe
16:00:17 [info] Module: D:\Jenkins\workspace\_VG-13572\output\vg.studiomax\bin\Debug\vgl_simulation_matrix_ut.exe is selected because it matches selected pattern: *ut.exe
16:00:17 Error: bad allocation
16:00:17 Press any key to continue... 
16:00:17 D:\Jenkins\workspace\Sim_UT_Cov>exit 1 
16:00:17 Build step 'Execute Windows batch command' marked build as failure
```

Could you reproduce the issue on a toy example?
yes

## Attached file
[LastCoverageResults.log](https://github.com/OpenCppCoverage/OpenCppCoverage/files/2017814/LastCoverageResults.log)
Attach the log file *LastCoverageResults.log*, located in your current folder.

Can you please make the memory allocations around loading the EXE more robust? Thanks.

**Comment by OpenCppCoverage** [comment]
Hello,

Thank you for reporting the issue.

I have just done the following test:
- Install Jenkins 2.107.3
- Create an Hello World program with Visual Studio 2017 (15.7.1)
- Start a Jenkins job that run the Hello World application with OpenCppCoverage 0.9.7.
=> The coverage is ok without the ``bad allocation`` error.

Can you perform the following tests to help me reproducing the issue?
1. Can you try with OpenCppCoverage 0.9.7?
2. Can you create an Hello World application with Visual Studio and run this application with OpenCppCoverage on Jenkins?
3. If you do not have the bad ``allocation error` in step 2, can you create a toy example that have this error and upload it?
4. I noticed you used Windows 7. Did you try to run OpenCppCoverage without Jenkins on Windows 7 computer?

OpenCppCoverage

**Comment by dzolee** [comment]
Hello there,

Thanks for the time you‘ve invested. I will have time next week, I will collect the infos you requested. 

Yes, the test EXEs all run without the error if I do not start it from the Jenkins job. The Win7 PC is my main PC, and OpenCppCoverage runs fine on it, also creates coverage for the „problematic“ test App and many more without error.

One more thing to the bad allocation: the „problematic“ EXE causes the bad alloc (only with OpenCppCoverage under Jenkins!) if I have a vector assignment in one test case. It is a std vector of doubles, with a size of 5 or 6.
I copy the vector of 5 elements to an empty vector like:
v2 = v1;
The strange thing is, it does not crash when it comes to this part of the code, but it seems to me that during program startup. I will experiment with different linker options (how is std linked to OpenCppCoverage or to the test program)

**Comment by dzolee** [comment]
Hello there,

some more infos as they come in:
-yes it happens with 0.9.7 as well.
-it is reproducible in a certain setup: the Jenkins job executes a command line, which calls OpenCppCoverage which launches cmd.exe with a batch parameter. The batch file, iterates through all unit test executables and starts them.
(I wanted to create a summary coverage of all tests, but the merge option did not work, it just overwrites the input coverage file.)

I see the error output has changes slightly in the new version:
09:19:19 [error] Error: bad allocation

I would love to debug into it, but I still cannot compile the project (NuGet problems) !! :(

**Comment by dzolee** [comment]
Hello there,

I have found a workaround, so I can run the coverage for my test programs.
Basically, the problem comes when I use OpenCppCoverage to start the cmd.exe which I use to start a batch file, which iterates through unit test EXEs with a for loop. Explained:

OpenCppCoverage --cover_children <some other params> -- cmd.exe /c loop.bat

The batch uses a for loop and starts the unit tets.
The reason I wrote it this way, is that I wanted one coverage file, and somehow I haven't succeeded with merging files.

Now I changed the above logic a bit:
I use a batch for loop to find the test EXEs and, start OpenCppCoverage individually for all EXEs. As a result, I have many output files, but fortunately, the Cobertura Jenkins plugin aggregates the input files so I have the desired coverage display in Jenkins.

To sum up the above infos:
-The bad alloc error is reproducible with "some" test programs, but only if I use the first approach (with cmd.exe). I cannot isolate the problem to a single test program, the whole chain with cmd.exe and batch is required.
-If I use the same "cmd.exe" logic from the command line (not from Jenkins), then there is NO bad alloc, no errors.

A few years back, I had some suspicious crashes, with Jenkins and another debugger-based coverage tool (called CoverageValidator), if I remember correctly, the guy said some environment variables were not accessible under Jenkins. They provided a fix, but that is a different story.

Basically I am happy with the above workaround, if I can ever manage to compile the tool locally, I will probably give it another go and try to debug into it.

I wish you good luck anyway, keep up the good work.

**Comment by dzolee** [comment]
Thank you too, now I have managed to produce a local debug build, I will try to gather more infos.

**Comment by dzolee** [comment]
I cannot reproduce it with my local build.
I think some kind of linker option difference between STD or something that might use STD, caused the problem.
I will keep an eye on it but for now, I am happy.
Thanks

**Comment by OpenCppCoverage** [comment]
Hello,

I am closing this issue as it is not active anymore. Feel free to reopen it or create a new one if needed.

OpenCppCoverage
