### ISSUE TITLE
Extend Cobertura export interface

### ISSUE THREAD

**Issue by dzolee** [OpenCppCoverage/OpenCppCoverage#51]
Hello,

this is a mix of a feature request and technical question.
I would like to specify the "package" name for the generated Cobertura report. I have found the location in the exporter and I can modify the string, but I would like a technically better, configurable solution. Like a command line option. I need to set it to a specific value for all generated reports.

For this, the parameter should be somehow passed to the exporter. Which solution would fit into the existing logic, in your opinion? Is it OK to extend the IExporter, and then how? Maybe other exporters would also receive parameter(s) in the future.

**Comment by OpenCppCoverage** [comment]
Hello,

If I understand correctly, this is a specific feature. I try to avoid adding a specific command line flag that will be visible to all users.
What about writing a small script that update the Cobertura file generated by OpenCppCoverage instead?
You do not have to maintain your own branch or apply the patch on each release.

I hope it will help,

OpenCppCoverage

**Comment by dzolee** [comment]
Yes, it's a good tip.

**Comment by OpenCppCoverage** [comment]
Hello,

I am closing this issue as it is not active anymore. Feel free to reopen it or create a new one.

OpenCppCoverage.
