### ISSUE TITLE
vstest.conosole can not be run within the plugin, only from a console

### ISSUE THREAD

**Issue by dimevit** [OpenCppCoverage/OpenCppCoverage#55]
Hi,

is there a way to run the very same command:

OpenCppCoverage --cover_children --sources YOUR_SOURCE -- "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" /Platform:x64 x64/debug/UnitTests.dll

within the VisualStudio plugin? 

Sofar I manage to run it only from the command line but it would be nice to have it run from the plugin so that I can see the results within the cpp files. 

thanks

**Comment by OpenCppCoverage** [comment]
Hello,

I can reproduce the issue. I am working on a new release for the plugin. I will do my best to include this fix.

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

It is fixed in [OpenCppCoverage plugin 0.9.6.0](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/releases/tag/0.9.6.0).
Feel free to reopen the issue if the problem still exists.

OpenCppCoverage
