### ISSUE TITLE
Look for program_to_run in environment variable %PATH%

### ISSUE THREAD

**Issue by a-andre** [OpenCppCoverage/OpenCppCoverage#6]
## Describe your environment
- Version of OpenCppCoverage: 0.9.6.1
- Architecture (x86/ x64): x64
- Windows version: 10

## Describe your problem
Steps to reproduce:
1. Install CMake with `ctest.exe`and add the location to the PATH variable
2. Run `OpenCppCoverage.exe -- ctest.exe`
3. Output: Error: Program to run "ctest.exe" does not exist
It works if `ctest.exe` is replaced by the absolute path but that is not convenient.

**Comment by OpenCppCoverage** [comment]
Hello,

Thank you for this feedback. 
I will add this feature in the next release if it does not require big changes.

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

It should be fixed in [OpenCppCoverage 0.9.7.0](https://github.com/OpenCppCoverage/OpenCppCoverage/releases/tag/release-0.9.7.0).

OpenCppCoverage
