### ISSUE TITLE
Question / Note - execution path coverage or unit test coverage?

### ISSUE THREAD

**Issue by Laro88** [OpenCppCoverage/OpenCppCoverage#62]
I think I have mislead myself into thinking that OpenCppCoverage provides a coverage metric of the unit tests. My current understanding is that what is measured is all paths of execution originating from the executable - and not what is actually executed from the unit tests. This maybe ok - but in some cases there may be a couple of helper classes inside the unit test project that mocks / stubs stuff out - and this may lead to incorrect coverage reporting (classes being used without actually being called by a test, lets call it false positives)

I would advice to put in a clarification for others that find OpenCppCoverage recommended for unit test coverage.

**Comment by OpenCppCoverage** [comment]
Hello,

OpenCppCoverage reports the executed lines. 
Please make sure your program is not compiled in release as the aggresive optimisations can lead to a surprizing coverage (Same as with your debugger).
If you use a static library, please see the latest messages [here](https://github.com/OpenCppCoverage/OpenCppCoverage/issues/52).

If you still have an issue, please provide more information, ideally a small application with your failed coverage.

OpenCppCoverage
