### ISSUE TITLE
opencppcoverage for .c source files

### ISSUE THREAD

**Issue by mp0712** [OpenCppCoverage/OpenCppCoverage#68]
I am working on .c source files. When I ran opencpp coverage for a testapplication.sln file I am getting total lines covered as 0. I am giving testapplication.exe path and all the .c source files paths in the sources. Can anyone please guide me.
OpenCpp coverageversion: 0.9.7.0

**Comment by OpenCppCoverage** [comment]
Hello,

First ``--sources`` is a way to select source files. OpenCppCoverage the discovers source files from PDB files.
I have just tested and OpenCppCoverage has no issue with .c file.

Can you try to run OpenCppCoverage without any filters(no ``--sources``, ``--modules``)?
- If you have some coverage, please read carefully the meaning of ``--sources`` and ``--modules``.
- If you have no coverage, can you also create a small console application that reproduce the issue?

I hope it will help,

OpenCppCoverage

**Comment by mp0712** [comment]
Hi,
Thank you for your response. yeah I figured it out. I forgot to close the issue. It is working fine for .c files too. The problem is with my debug information.
