### ISSUE TITLE
Add an option to write the coverage to standard output

### ISSUE THREAD

**Issue by a-andre** [OpenCppCoverage/OpenCppCoverage#7]
I want to run OpenCppCoverage as part of a CI. For Linux I use `gcovr` but that is not available for a Visual Studio Project.

You can find an example output of gcovr here: http://gcovr.com/guide.html
At the moment I only care about the `TOTAL` line. It would be nice if you could provide such an output and if possible use the same format, so the same regex (`^TOTAL.*\s+(\d+\%)$`) can be used to parse the result.

Thank you.

**Comment by OpenCppCoverage** [comment]
Hello,

For CI, OpenCppCoverage supports the cobertura format which works for example on Jenkins.
Unfortunately, there is no plan to support gcov format.

Maybe, there is a converter between cobertura and gcov formats.
If not, I suggest exporting to xml format with ```--export_type=cobertura```:
  - Find the right regular expression to have the total line number
  - OR write a small script to compute the value you want from the XML.

I hope it will help,

OpenCppCoverage

**Comment by a-andre** [comment]
Is there an option to write the cobertura format directly to the terminal without or additional to storing the result in a file?

**Comment by OpenCppCoverage** [comment]
There is no option to write to the standard output. Maybe using the dos command ```type``` can help (the equivalent of linux ```cat``` command).

OpenCppCoverage

**Comment by janosvitok** [comment]
You can chain commands in Windows with && now (the same way as in unix for thousands of years). `opencppcoverage arg1 arg2... argn && type report.xml` will probably do what you want.

**Comment by a-andre** [comment]
Thanks.

`&&` doesn't work using the powershell, but there is probably something similar.
