### ISSUE TITLE
Build third party dependencies fail due to vcpkg bzip2

### ISSUE THREAD

**Issue by Alex-PLACET** [OpenCppCoverage/OpenCppCoverage#73]
The BuildThirdPartyDependencies.bat script fail due to an invalid link to bzip2 in vcpkg.
Newer version of vcpkg should be used.

**Comment by WimLeflere** [comment]
fixed vcpkg issue: https://github.com/Microsoft/vcpkg/issues/4319

**Comment by OpenCppCoverage** [comment]
Hello,

Please see https://github.com/OpenCppCoverage/OpenCppCoverage/issues/77
