### ISSUE TITLE
Release build code coverage

### ISSUE THREAD

**Issue by aashraybhandar1** [OpenCppCoverage/OpenCppCoverage#74]
Is any feature or fix that can be looked at to ensure accurate code coverage for the release build?

**Comment by OpenCppCoverage** [comment]
Hello,

I have updated section [Release versus Debug](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki#release-versus-debug) to give more information about release issues.

Please let me know if you have any idea to improve the code coverage quality for a release build.

OpenCppCoverage
