### ISSUE TITLE
Build third party dependencies fail due to 7zip

### ISSUE THREAD

**Issue by WimLeflere** [OpenCppCoverage/OpenCppCoverage#77]
The BuildThirdPartyDependencies.bat script fail due to an invalid hash for 7zip in vcpkg.

This seems to be fixed in a newer version of vcpkg.
https://github.com/Microsoft/vcpkg/issues/4663

**Comment by OpenCppCoverage** [comment]
Hello,

It is fixed by https://github.com/OpenCppCoverage/OpenCppCoverage/commit/73dd5b5801ee6430d27fd55dd808f03b3be1d25a.

Feel free to reopen the issue if it does not work for you.

OpenCppCoverage
