### ISSUE TITLE
Support of UWP applications

### ISSUE THREAD

**Issue by mhandb** [OpenCppCoverage/OpenCppCoverage#79]
Today, it is not possible to do code coverage on UWP Test applications. Even with the Microsoft Tools.
But it would be possible, as it is possible to debug it.
The idea would be to
- Start the UWP app in prelaunch mode
- Use DebugActiveProcess to attach to the process
- Run the UWP app 

It would be nice to have such feature. 
At least for me.

**Comment by OpenCppCoverage** [comment]
Hello,

It would be probably a nice feature but I have a limited availability to work on this project and so I am trying to stay focused on small changes.
Maybe you can try updating the source code to have a "hacked version" that handle your UWP application.  

OpenCppCoverage

**Comment by oggy22** [comment]
Hi @mhandb , I know it's been >5y, but I am curious about your 3 steps for UWP. I am facing exactly the same issue where I want to get coverage for UWP app and I've filed a similar issue #186 and have implemented a hack for that #187 .

I guess I am not sure I understand `Start the UWP app in prelaunch mode` and how you can communicate back the process id? Thanks!
