### ISSUE TITLE
Continue on exit code !=0

### ISSUE THREAD

**Issue by amai2012** [OpenCppCoverage/OpenCppCoverage#8]
## Describe your environment
- Version of OpenCppCoverage: 0.9.6.1
- Architecture (x86/ x64): x64
- Windows version: 7

## Describe your problem
Steps to reproduce:
1. Run opencppcoverage on test application (kind of unit testing)
2. testa pplication exits with return code 1 - which means a test failure.
3. Further processing fails, via --input-coverate the problem even spreads further

I'd like OpenCppCoverage to continue - maybe based on a command line flag --ignore-exit-codes

**Comment by OpenCppCoverage** [comment]
Hello,

I created ConsoleApplication2.exe from the following code

```
#include <iostream>

int main(int argc, char** argv)
{
	if (argc == 2)
	{
		auto exitCode = std::atoi(argv[1]);
		std::cout << "Exit: " << exitCode << std::endl;
		return exitCode;
	}
	std::cout << "Invalid Number of arguments" << std::endl;
    return 1;
}
```

Then I ran the following command. It creates ``ConsoleApplication2.cov`` prints ``Exit: 1`` and exit with code 1.
```OpenCppCoverage.exe --source ConsoleApplication --export_type=binary -- ConsoleApplication2.exe 1```

I ran again OpenCppCoverage with _--input_coverage_
```
OpenCppCoverage.exe --source ConsoleApplication --input_coverage ConsoleApplication2.cov -- ConsoleApplication2.exe
```
The previous command prints "Invalid Number of arguments", exits with code 1 and creates HTML report with 100% of coverage.

Can you describe more precisely your steps to reproduce and what is exactly your issue?
Any chance you used a BAT file and chain command with &&?

OpenCppCoverage

**Comment by amai2012** [comment]
Indeed my report was not correct.
It seems to create coverage but my scripts break because of OpenCppCoverage return a non-zero return code, which is handled as an error (actually it's being called from an ant script).

OpenCppCoverage seems to use the return code of the app being analyzed. How can I determine the success of OpenCppCoverage then?

**Comment by OpenCppCoverage** [comment]
Hello,

If OpenCppCoverage failed, it returns 1. I will try to use a more specific value in the next release.

I hope it can help,

OpenCppCoverage.

**Comment by amai2012** [comment]
I've seen other applications accepting a user-supplied error value to avoid any clash with error codes of the application being analyzed.

**Comment by OpenCppCoverage** [comment]
Thank for the suggestion.

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

I implemented a user-supplied error value but changed to a constant exit code when failed for the following reasons:
 - If the command line parsing failed, the user error code cannot be returned and so a specific exit code is still required.
 -  I try to avoid adding a new command line flag.
 -  It is hard to know which exit code an application returned and so hard to guaranty there is no clash.

OpenCppCoverage returns a specific error code when failed in master branch and this feature will be available in the next release.

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

OpenCppCoverage returns a specific error code in [OpenCppCoverage 0.9.7.0](https://github.com/OpenCppCoverage/OpenCppCoverage/releases/tag/release-0.9.7.0).

OpenCppCoverage

**Comment by Unicornum** [comment]
Ignore OpenCppCoverage error code for post-build event Visual Studio:

%COVERAGE_RUN% %PARAMS% 2> nul 1> nul
