### ISSUE TITLE
using --excluded_sources followed by --sources

### ISSUE THREAD

**Issue by mydeveloperday** [OpenCppCoverage/OpenCppCoverage#81]
**Before creating an issue, please make sure the answer is not in the [FAQ](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ).**

**This template is applied for all bug requests. Remove it for other general question or feature request.**

## Describe your environment
- Version of OpenCppCoverage:  0.9.7
- Architecture (x86/ x64):  x64
- Windows version:  10

## Describe your problem
Steps to reproduce:
1.  I want to analyse the coverage of just one or two files form a large directory not the whole directory
2.  run with --exclude_sources="*\<dir>\* " --sources="file_in_dir.*"
3.  this causes no sources to be found

sometimes you want to exclude a whole directory then bring a few back, same with modules

--excluded_modules="*.dll"  - modules="mydll.dll"

(seems to not analyze anything in mydll.dll because *.dll wins!)

From what I can tell both (include/exclude) sources and modules don't work in combination sometimes its much easier to exclude everything and then include the few files/modules you need.

Not sure if this is a bug or a feature request... (or if I've configured something wrong)

**Comment by OpenCppCoverage** [comment]
Hello,

The behavior of ``excluded_modules`` is defined [here](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Command-line-reference#--excluded_modules-arg) (It also applies for ``exclude_sources``).

> A module is selected if its path:
> *  contains at least one --modules pattern
> * does not contain a --excluded_modules pattern.

If you only want to select 2 files ``MyFile1.cpp`` and ``MyFile2.cpp`` you can use:
``--sources=MyFile1.cpp --sources=MyFile2.cpp``

Please let me know if I misunderstood your problem.

I hope it helps,

OpenCppCoverage
