### ISSUE TITLE
C++ Application cannot be started when instrumented with OpenCpp Coverage (0x80000003)

### ISSUE THREAD

**Issue by stefansta1** [OpenCppCoverage/OpenCppCoverage#82]
I use OpenCppCoverage with a large C++ 64 bit application. When I start the instrumented apllication I get an error message "The application was unable to start correctly (0x80000003).. I use an release build but with debug information.

**Comment by OpenCppCoverage** [comment]
Hello,

Did you use [--optimized_build](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Command-line-reference#--optimized_build)?

Does your application start, if you comment all the code in your main function?

OpenCppCoverage

**Comment by stefansta1** [comment]
Hi,

thank you for the response. I used the  --optimized_build and also try to start a build without optimization but I still get the error.
What do you mean with "comment all the code in the main function"?

**Comment by stefansta1** [comment]
Hi,

as additional information, I use Windows 7.

Thank you.

**Comment by OpenCppCoverage** [comment]
Hello,

Can you create an *Hello World* application as explained [here](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki#your-first-coverage) and check if you still have the same error:
 - If yes, can you reinstall OpenCppCoverage and check if it fails again?
 - If not, the issue should come from your code. Can you reproduce the issue on a small code? Using ``--verbose`` flag may help you spotting where the issue come from. 
 
Please let me know the outcome of these tests.
 
OpenCppCoverage

**Comment by stefansta1** [comment]
The error occurs on Windows 7, but not on Windows 10, where the application starts correctly
