### ISSUE TITLE
Merging binary.cov outputs (to generate HTML) with different source locations

### ISSUE THREAD

**Issue by MarcoWagner** [OpenCppCoverage/OpenCppCoverage#83]
## Describe your environment
- Version of OpenCppCoverage:  0.9.7.0
- Architecture (x86/ x64): x64
- Windows version: 10 (dev) / 7 (vm)

## Describe your problem
Steps to reproduce:
1. Create binary report on "dev" system
2. Create additional report and merge prev.cov report on "vm" system (--sources (network drive letter) and --substitute_pdb_source_path are set to absolute paths)
3. Report shows different pathes to source files causing the called code lines of the individual runs are not agregated.

**Comment by OpenCppCoverage** [comment]
Hello,

I have just added in the FAQ [Merging code coverage from different source locations](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ#merging-code-coverage-from-different-source-locations).

I hope it helps,

OpenCppCoverage

**Comment by MarcoWagner** [comment]
Thanks for your help but in my case adjusting the path is not feasible. I have already built a little tool which which merges the resulting cobertura files.
