### ISSUE TITLE
[error] Error: handleinformation.cpp:85 Cannot find path for the handle.

### ISSUE THREAD

**Issue by FGKD** [OpenCppCoverage/OpenCppCoverage#84]
## Describe your environment
- Version of OpenCppCoverage: 0.9.7.0 / Current Repository Head
- Architecture (x86/ x64): x64
- Windows version: 10.0.17134.590

## Describe your problem
Running certain Debug Build Unit Tests are causing the error message

>  [error] Error: handleinformation.cpp:85 Cannot find path for the handle.Zugriff verweigert

"Zugriff verweigert" translates to "Access denied".

This error has been ocurring to other people for several years already:

https://stackoverflow.com/questions/40233115/opencppcoverage-cannot-find-path-for-the-handle
http://opencppcoverage.codeplex.com/discussions/657681 (Page doesn't exist anymore)
https://stackoverrun.com/ja/q/11079605
https://libraries.io/github/onatbas/OpenCppCoverageTestFail

Running OpenCppCoverage with Admin rights didn't fix the issue.

When trying to debug the issue myself, i discovered that the error occurs in the GetFinalPathName function in HandleInformation.cpp.

It is caused by the GetFinalPathNameByHandle call failing.

The following files cause GetFinalPathNameByHandle to fail on our system:
* tbbmalloc_debug.dll (accessed as a symlink)
* C:\Windows\System32\cryptsp.dll
* C:\Windows\System32\rsaenh.dll
* C:\Windows\System32\bcrypt.dll
* C:\Windows\System32\cryptbase.dll

A possible repro for the four crypto Dlls being loaded is compiling code that contains the line

`boost::random_device rd;`

When trying to find the reasons for GetFinalPathNameByHandle failing when trying to resolve the filenames of certain files, I ran into this MSDN Page: https://docs.microsoft.com/en-us/windows/desktop/memory/obtaining-a-file-name-from-a-file-handle

Using parts of this code (CreateFileMapping -> MapViewOfFile -> GetMappedFileName), the filenames of the DLLs mentioned above could be resolved successfully.

I am currently using this version of the GetFinalPathName function internally, and all my issues are gone:

(Please excuse the slightly broken formatting, something with the markup isn't working right)

`std::wstring GetFinalPathName(HANDLE hfile)
		{
			std::vector<wchar_t> buffer(PathBufferSize);

      if (!GetFinalPathNameByHandle(hfile, &buffer[0], static_cast<int>(buffer.size()) - 1, VOLUME_NAME_NT))
      {
        // Fallback: Use File Mapping

        FILE_BASIC_INFO basicInfo;
        BOOL result;

        result = GetFileInformationByHandleEx(hfile, FileNameInfo, &basicInfo, sizeof(basicInfo));

        BOOL bSuccess = FALSE;
        TCHAR pszFilename[MAX_PATH + 1];
        HANDLE hFileMap;

        // Get the file size.
        DWORD dwFileSizeHi = 0;
        DWORD dwFileSizeLo = GetFileSize(hfile, &dwFileSizeHi);

        if (dwFileSizeLo == 0 && dwFileSizeHi == 0)
        {
          THROW(L"Cannot find path for the handle.");
        }

        // Create a file mapping object.
        hFileMap = CreateFileMapping(hfile,
          NULL,
          PAGE_READONLY,
          0,
          1,
          NULL);

        if (hFileMap)
        {
          // Create a file mapping to get the file name.
          void* pMem = MapViewOfFile(hFileMap, FILE_MAP_READ, 0, 0, 1);

          if (pMem)
          {
            if (!GetMappedFileName(GetCurrentProcess(),
              pMem,
              pszFilename,
              MAX_PATH))
            {
              THROW(L"Cannot get file name for mapped file.");
            }
          }
          else
          {
            THROW(L"Cannot create file mapping for the handle.");
          }

          CloseHandle(hFileMap);
        }
        else
        {
          THROW(L"Cannot create file mapping object.");
        }

        return std::wstring(pszFilename);
        //THROW_LAST_ERROR(L"Cannot find path for the handle.", GetLastError());
      }

			return &buffer[0];
		}
	}`

Alternatively, GetFinalPathNameByHandle could be completely removed and the other way of resolving the name could be used exclusively.

On the aforementioned MSDN Page is also more code after the GetMappedFileName that resolves the Device Name / Drive Letter in a slightly different way than OpenCppCoverages ComputeFilename function, but changing that part is not necessary.

Btw thank you very much for making it very easy to build OpenCppCoverage myself, the BuildThirdPartyDependencies script and the existing sln/vcxproj files were a blessing!

**Comment by OpenCppCoverage** [comment]
Hello,

Thank you very much for the bug analyze and for providing a solution. I never reproduce the issue and as you said, it was a blocking issue for several users!

I used ``GetMappedFileName`` but I changed to ``GetMappedFileName``  in [this commit](https://github.com/OpenCppCoverage/OpenCppCoverage/commit/24544b351949073cad08d9b06c8b7acdca935819?diff=split).
I need to check whether ``GetMappedFileName`` works for network drives but I can use ``GetFinalPathName`` and if the function failed try with ``GetMappedFileName``.


OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

I tried to reproduce the issue with ``boost::random_device rd;`` or by calling one function from ``tbbmalloc_debug.dll``.
I did not reproduce the issue, maybe boost should be compiled with intel tbb.
Anyway, on master branch, OpenCppCoverage uses ``GetFinalPathName`` and ``GetMappedFileName`` as a fallback.

Thank you very much for this investigation!

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

OpenCppCoverage [0.9.8.0](https://github.com/OpenCppCoverage/OpenCppCoverage/releases/tag/release-0.9.8.0) should fix the problem. Please let me know if it is not the case.

OpenCppCoverage
