### ISSUE TITLE
Q: Comments in config file

### ISSUE THREAD

**Issue by LeslieGerman** [OpenCppCoverage/OpenCppCoverage#88]
**Before creating an issue, please make sure the answer is not in the [FAQ](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ).**
Done - not found.

Is it possible to use comments, or put some lines in comment in the config file?

If not, I suggest to introduce the # character, like in Linux shells...
Regards.

**Comment by OpenCppCoverage** [comment]
Hello,

The config file is handled by boost program option and so a line starting with ``#`` is ignored.

I hope it helps,

OpenCppCoverage

**Comment by LeslieGerman** [comment]
Cool, thanks!
😃 
I suggest to add this to the FAQ or to the [docu of --config_file](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Command-line-reference#--config_file-arg) option.

Bests!

**Comment by OpenCppCoverage** [comment]
Hello,

The documentation was updated.

OpenCppCoverage
