### ISSUE TITLE
Any plan for supporting VS2019?

### ISSUE THREAD

**Issue by ryanplanet** [OpenCppCoverage/OpenCppCoverage#89]
Hello All,

The new Visual Studio has been released since 4 months ago, and now I am using it.
I used to see how my project's coverage is through this useful tool but since I updated VS 2015 to 2019, It seems that OpenCppCoverage has not supported new version.

May I ask 'is there any plan to support VS2019?'

**Comment by OpenCppCoverage** [comment]
Hello,

OpenCppCoverage works with VS2019, at least on a simple project.
If you speak about supporting VS2019 **for the plugin**, I will work on it this week.

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

Please see [here](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/issues/29).

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

[OpenCppCoverage plugin version 0.9.7.0](https://marketplace.visualstudio.com/items?itemName=OpenCppCoverage.OpenCppCoveragePlugin&ssr=false#overview) is available for Visual Studio 2019.

OpenCppCoverage.
