### ISSUE TITLE
Coverage for a non console application with managed and c++

### ISSUE THREAD

**Issue by jmecosta** [OpenCppCoverage/OpenCppCoverage#9]
Hi,

Apologies if i havent find this question in the codeplex discussions and here. The closest would be vstest execution. but i still get a error from the opencppcoverage

Project "C:\prod\structures\Test\FarmiTests\Smoke.msbuild" on node 1 (default targets).
RunUsingDefaultEnvFarmiIni:
  Run Nunit Test Assembly
  ProjectDir
  TeamcityCheckoutFolder
[info] Module: C:\prod\structures2\BuildDrop\Work\bin_x64\Test\FarmiTask\FarmiAdapterTask.dll is selected because it matches selected pattern: *
Error: c:\program files (x86)\jenkins\workspace\opencppcoverage\cppcoverage\filedebuginformation.cpp:66 Error when calling SymFromAddr

Basically our application is not console application has c#, c++/cli, and c++. We have many set of tests written in c++ or c#. I am trying to use OpenCppCover to do Test Impact Analysis, so i would require to retrieve c++ coverage information for all possible test, this includes functional tests that are created in C# or in any other technology.

We have a working solution using Bullseye, however i dont like the penalty of having to instrument the binaries to collect coverage. So in theory the best would be to allow to attached to process before running a test collect coverage and detach. This would also would only filter the coverage created by the application starting up.

If this is not possible, it would be good already to just be possible to run tests from console (that launches the application in separate process ) and collect the coverage then

thanks for the help and keep up the good work

**Comment by OpenCppCoverage** [comment]
Hello,

I did the following test:
- Create a managed C++ CLI Test project (``ManagedTests.dll``)
- Create a normal C++ shared dll project (``SharedDll.dll``)
- ``ManagedTests.dll`` call the function ``foo`` located in ``SharedDll.dll``.

If I run the following command, I get an error (System.InvalidProgramException in my case but the error can be different).
``OpenCppCoverage --modules ManagedTests.dll --modules SharedDll.dll -- vstest.console.exe ManagedTests.dll``

If I select only the native dll, the tests and the coverage are ok. 
``OpenCppCoverage --modules SharedDll.dll -- vstest.console.exe ManagedTests.dll``

So if you use ``vstest.console.exe`` and use ``--modules`` only for your native libraries, it should work.

Do you use ``vstest.console.exe`` to run your tests? If not, maybe CLR hosting can help. I did not have the time to test it but it should does the same job as ``vstest.console.exe``.

PS: I may find a way to detect if a dll is managed or not and so I could exclude them in the future.

I hope it will help,

OpenCppCoverage

**Comment by jmecosta** [comment]
@OpenCppCoverage thanks for the reply. i could now proceed a bit further. indeed the modules does the trick. As you mention detecting if dll is managed or not should save loads of maintenance, ive now been playing with it and keeps failing since i need to use --excluded_modules since the if using for example --modules Common.dll it will match ACommon.dll etc. So having this detected automatically should be really good.

Another more critical issue is related with the several locks (or extremely slow) i observe when adding more modules, the application is quite big. do you have any idea of the impact of opencppcover in the speed of overall application (this is simply running the application with OpenCppCover attached to it)?

Locked in some of these:
[info] Module: C:\prod\BuildDrop\Work\bin_x64\Module.dll is selected because it matches selected pattern: Module.dll

another minor thing. I get a warning for each of the file like this:
[warning] c:\prod\file.cpp line 1316 does not exist, skipped

file.cpp has 1315 lines. so its expected to not exist. One warning per file.

thanks for the help

**Comment by OpenCppCoverage** [comment]
Hi,

_"ive now been playing with it and keeps failing since i need to use --excluded_modules since the if using for example --modules Common.dll it will match ACommon.dll"_
When running your program under Visual Studio, you can see all dll loaded in the output window. Also, using _--modules_ and add it one by one may be easier than using _--excluded_modules_.

_"Another more critical issue is related with the several locks (or extremely slow)"_
I am working on it and I already did a first big change. 
Do you want I send you a beta version when done this week or next week?

_"another minor thing. I get a warning for each of the file like this:
[warning] c:\prod\file.cpp line 1316 does not exist, skipped"_
You can safely ignore this warning and I will remove this message. The compiler generates code at a line that does not exist in the file.

I hope it will help,

OpenCppCoverage

**Comment by jmecosta** [comment]
Sure, you can send me. The performance is @ real blocker for us

Regarding the --modules, autodetection would be nice to have but yes I can
work it out with a bit of maintenance

**Comment by OpenCppCoverage** [comment]
Hello,

Here is a beta version with several improvements on startup duration.
I also implemented quickly a feature to disable managed dll. 

Can you give me the startup time for OpenCppCoverage 0.9.6.1 versus OpenCppCoveragex64-Beta on your program?
Are managed libraries excluded correctly?

Note that _--optimized_build_ is broken and I only did a few tests so you may see some errors :).

OpenCppCoverage
[OpenCppCoveragex64-Beta.zip](https://github.com/OpenCppCoverage/OpenCppCoverage/files/1489347/OpenCppCoveragex64-Beta.zip)

**Comment by jmecosta** [comment]
alright, great. i will post the results later this week. thanks

**Comment by jmecosta** [comment]
@OpenCppCoverage hard to say if the beta version is faster, i think its a bit faster. For a dll of 30 Mb (build in release) it takes in old version 2m:30s, that one i measure since it crashes right after because of a module that is not excluded. in new version it might be around 2m. however it does not crash and it just gets stuck after doing something that i dont understand and the application does not proceed

[info] Module: C:\prod\BuildDrop\Work\bin_x64\SharedDll.dll is selected because it matches selected pattern: SharedDll.dll
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped
[warning] c:\program files (x86)\microsoft visual studio 14.0\vc\include\vector line 16707566 does not exist, skipped

it would be if you could include in the log, the timestamps so we could also compare

thanks

**Comment by OpenCppCoverage** [comment]
Hello,

Thank you for the feedback.
Timestamps are included in the log file _LastCoverageResults.log_.

Did you find your issue?
If not, I suggest disabling the last module (Last ``[info] Module: XXX.dll is selected because it matches selected pattern``) before the issue. If you are able to isolate the problem, I can probably fix it.

Let me know if I can help,

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

[OpenCppCoverage 0.9.7.0](https://github.com/OpenCppCoverage/OpenCppCoverage/releases/tag/release-0.9.7.0) ignores managed modules and the initialization duration is reduced.
I am closing this issue as it is not active anymore.
Let me know if you have more information on your problem.

OpenCppCoverage
